# Build our CellXGene training and validation sets

Based on what we learned in the EDA notebook, we build up training and validation sets with which to train a model

In [8]:
%run notebook_setup.ipynb

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
autoreload enabled
repo_dir set to /root/GenePT-tools
File already exists at /root/GenePT-tools/data/GenePT_emebdding_v2.zip
Extracting files...
Extracting GenePT_emebdding_v2/
Skipping GenePT_emebdding_v2/NCBI_UniProt_summary_of_genes.json - already exists with same size
Skipping GenePT_emebdding_v2/GenePT_gene_embedding_ada_text.pickle - already exists with same size
Skipping GenePT_emebdding_v2/GenePT_gene_protein_embedding_model_3_text.pickle. - already exists with same size
Skipping GenePT_emebdding_v2/NCBI_summary_of_genes.json - already exists with same size
Extraction complete!
Skipping embedding_original_ada_text.parquet - already exists
Skipping embedding_original_large_3.parquet - already exists
Skipping embedding_associations_age_cell_type_drugs_pathways_openai_large.parquet - already exists
Skipping embedding_associations_age_drugs_pathways_openai_large.parquet - already exists
Skipping embedding_associations_cell_type_openai_large.parquet - already exists
Skipping embedding_associations_cell_type_tissue_drug_pathway_openai_large.parquet - already exists
Setup finished!
data_dir set to /root/GenePT-tools/data

## Load CellXGene V2 metadata

I extracted some metadata contained in the CellXGene V2 AnnData files using https://github.com/honicky/anndata-metadata
and saved it in `cellxgene_v2_metadata_v2.parquet`

In [9]:
import pandas as pd

metadata_pdf = pd.read_parquet(data_dir / "cellxgene_v2_metadata_v2.parquet")

In [10]:
import json

def aggregate_obs_counts(pdf, obs_count_name):
  all_obs_counts = {}
  for json_obj in pdf.obs_counts:
    obs_counts = json.loads(json_obj[obs_count_name])
    for key, value in obs_counts.items():
      if key in all_obs_counts:
        all_obs_counts[key] += value
      else:
        all_obs_counts[key] = value

  obs_counts_pdf = pd.DataFrame(all_obs_counts.items(), columns=[obs_count_name, 'count']).set_index(obs_count_name).sort_values('count', ascending=False)
  return obs_counts_pdf

cell_type_counts_pdf = aggregate_obs_counts(metadata_pdf, 'cell_type')
cell_type_counts_pdf.head(50)

                                                      count
cell_type
neuron                                              7271693
L2/3-6 intratelencephalic projecting glutamater...  4310965
oligodendrocyte                                     3556599
fibroblast                                          2267012
unknown                                             2159597
CD4-positive, alpha-beta T cell                     2045255
CD8-positive, alpha-beta T cell                     1952771
macrophage                                          1950346
classical monocyte                                  1591535
T cell                                              1472348
radial glial cell                                   1408275
natural killer cell                                 1383190
B cell                                              1323108
glutamatergic neuron                                1296255
malignant cell                                      1262249
endothelial cell                                    1111872
naive thymus-derived CD4-positive, alpha-beta T...  1032974
astrocyte                                            979799
monocyte                                             941977
alveolar macrophage                                  891050
fibroblast of mammary gland                          833781
oligodendrocyte precursor cell                       793760
neuroblast (sensu Vertebrata)                        791811
luminal adaptive secretory precursor cell of ma...   755338
central memory CD4-positive, alpha-beta T cell       742151
microglial cell                                      739025
cardiac muscle cell                                  729517
mesenchymal cell                                     687663
regular ventricular cardiac myocyte                  677421
pvalb GABAergic cortical interneuron                 677099
VIP GABAergic cortical interneuron                   670503
CD14-positive monocyte                               624645
sst GABAergic cortical interneuron                   611911
capillary endothelial cell                           581420
cerebellar granule cell                              576872
neural cell                                          564984
pulmonary alveolar type 2 cell                       562360
pericyte                                             539962
luminal hormone-sensing cell of mammary gland        534342
epithelial cell of proximal tubule                   533396
glioblast                                            508786
epithelial cell                                      494149
effector memory CD8-positive, alpha-beta T cell      491798
mural cell                                           487831
fallopian tube secretory epithelial cell             471766
vein endothelial cell                                469705
CD16-positive, CD56-dim natural killer cell, human   469505
basal cell                                           462497
lamp5 GABAergic cortical interneuron                 459931
naive B cell                                         448843

## Load AnnData unstructured metadata fields

We created `descriptions.parquet` in the EDA notebook.

In [11]:
descriptions_pdf = pd.read_parquet(data_dir / "cellxgene" / "descriptions.parquet")

### Double check that we can join `metadata_pdf` and `descriptions_pdf`

In [12]:
print(metadata_pdf.index)
print(descriptions_pdf.index)

cominbed_metadata_pdf = pd.concat([metadata_pdf, descriptions_pdf], axis=1)

RangeIndex(start=0, stop=961, step=1)
RangeIndex(start=0, stop=961, step=1)

In [13]:
cominbed_metadata_pdf[cominbed_metadata_pdf.published_at > '2023-05-08'].shape

(393, 48)

# selection criteria

* 10K cells for each cell type with enough
  * select uniforming across files 
* hold out 10% for testing for other types
* filter out tabula sapiens 
* test set should be past 2023-05-08 when scGPT was trained
  * 393 files
  * 152 genes in our list are not represented in these files

In [14]:
import numpy as np

cell_counts_pdf = pd.DataFrame({
  row['cell_type']: metadata_pdf.obs_counts.apply(lambda x: json.loads(x['cell_type']).get(row['cell_type'], 0))
  for i, row in np.minimum(cell_type_counts_pdf[(cell_type_counts_pdf['count'] > 500)], 10_000).reset_index().iterrows()
})

In [15]:
sum(cell_counts_pdf[cominbed_metadata_pdf.published_at > '2023-05-08'].sum() == 0)

152

In [16]:
cell_counts_pdf[cominbed_metadata_pdf.organism.apply(lambda x: len(x) == 1 and x[0]['label'] == 'Homo sapiens')].shape

(820, 738)

## We're ready to filter the metadata and cell counts

In [17]:
human_only_x10_metadata_pdf = cominbed_metadata_pdf[
    (cominbed_metadata_pdf.organism.apply(lambda x: len(x) == 1 and x[0]['label'] == 'Homo sapiens'))
    & (cominbed_metadata_pdf.assay.apply(lambda x: all(a['label'].startswith('10x') for a in x)))
  ].reset_index(drop=True)
human_only_x10_cell_counts_pdf = cell_counts_pdf[
    (cominbed_metadata_pdf.organism.apply(lambda x: len(x) == 1 and x[0]['label'] == 'Homo sapiens'))
    & (cominbed_metadata_pdf.assay.apply(lambda x: all(a['label'].startswith('10x') for a in x)))
  ].reset_index(drop=True)

test_file_indices = human_only_x10_metadata_pdf[human_only_x10_metadata_pdf.published_at > '2023-05-08'].cell_type.apply(lambda x: len(x)).sort_values(ascending=False)[:100].index
# cominbed_metadata_pdf[cominbed_metadata_pdf.published_at > '2023-05-08'].cell_type[0]

In [18]:
human_only_x10_cell_counts_pdf.iloc[test_file_indices].shape

(100, 738)

In [19]:
human_only_x10_cell_counts_pdf.iloc[~human_only_x10_cell_counts_pdf.index.isin(test_file_indices)].head()
# test_file_indices

,neuron,L2/3-6 intratelencephalic projecting glutamatergic neuron,oligodendrocyte,fibroblast,unknown,"CD4-positive, alpha-beta T cell","CD8-positive, alpha-beta T cell",macrophage,classical monocyte,T cell,...,endothelial cell of sinusoid,epithelial cell of uterus,precursor cell,B-1a B cell,"CD34-positive, CD56-positive, CD117-positive common innate lymphoid precursor, human",ON retinal ganglion cell,kidney collecting duct cell,fibroblast of lymphatic vessel,brush cell of epithelium proper of large intestine,adipocyte of epicardial fat of left ventricle
0,9022,0,635,25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,5399,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,158,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,19391,6532,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Restructure so that we can pull out the right number of cells per file

In [20]:
training_counts = []

for cell_type in human_only_x10_cell_counts_pdf.columns:
    if cell_type == 'unknown':
        continue
    # Exclude test indices for training
    train_df = human_only_x10_cell_counts_pdf.iloc[~human_only_x10_cell_counts_pdf.index.isin(test_file_indices)]
    # Only keep rows where this cell type has > 0 cells
    counts_pdf = train_df[train_df[cell_type] > 0][[cell_type]].reset_index(drop=False)
    counts_pdf.columns = ['index', 'cell_count']
    counts_pdf['cell_type'] = cell_type

    total_cell_count = counts_pdf['cell_count'].sum()
    num_rows = len(counts_pdf)

    if total_cell_count <= 10000:
        # If under or equal to 10,000, take all
        selected = counts_pdf.copy()
    else:
        # Evenly divide 10,000 among rows
        base_share = 10000 // num_rows
        remainder = 10000 % num_rows

        # Assign base_share to each row, and distribute the remainder
        counts_pdf['take_cells'] = base_share
        if remainder > 0:
            counts_pdf.loc[counts_pdf.index[:remainder], 'take_cells'] += 1

        # For each row, take up to the minimum of take_cells and available cells
        counts_pdf['cell_count'] = counts_pdf[['take_cells', 'cell_count']].min(axis=1)

        # If some rows can't provide their full share, redistribute the leftover
        leftover = 10000 - counts_pdf['cell_count'].sum()
        while leftover > 0:
            # Find rows that still have available cells
            mask = counts_pdf['cell_count'] < train_df.loc[counts_pdf['index'], cell_type].values
            if not mask.any():
                break  # No more cells to take
            for idx in counts_pdf[mask].index:
                available = train_df.loc[counts_pdf.at[idx, 'index'], cell_type]
                if counts_pdf.at[idx, 'cell_count'] < available:
                    counts_pdf.at[idx, 'cell_count'] += 1
                    leftover -= 1
                    if leftover == 0:
                        break

        selected = counts_pdf[['index', 'cell_type', 'cell_count']]

    training_counts.append(selected)

In [21]:
training_counts_pdf = pd.concat(training_counts)
training_counts_pdf

    index                                          cell_type  cell_count
0       0                                             neuron          68
1      13                                             neuron          68
2      16                                             neuron          68
3      18                                             neuron          68
4      32                                             neuron          68
..    ...                                                ...         ...
2     368  CD34-positive, CD56-positive, CD117-positive c...         395
0     579                           ON retinal ganglion cell         549
0     471                        kidney collecting duct cell         420
1     717                        kidney collecting duct cell         125
0      99      adipocyte of epicardial fat of left ventricle         523

[5068 rows x 3 columns]

In [22]:
human_only_x10_metadata_pdf[human_only_x10_metadata_pdf.filename.str.contains("ff4cfa86-9c0c-4b7c-abd6-90547657d04f")]

,file_size,main_groups,cell_count,gene_count,obs_contents,var_contents,x_storage,embeddings,pairwise_relationships,expression_layers,...,self_reported_ethnicity,sex,spatial,suspension_type,tissue,title,tombstone,visibility,x_approximate_distribution,batch_condition
741,246620277,"[X, layers, obs, obsm, obsp, uns, var, varm, v...",9799,24855,"[Phase, _index, assay, assay_ontology_term_id,...","[feature_biotype, feature_is_filtered, feature...","{'chunk_size': [20497], 'components': ['data',...","[X_pca, X_umap]",[],[lognorm],...,"[{'label': 'European', 'ontology_term_id': 'HA...","[{'label': 'female', 'ontology_term_id': 'PATO...",None,[nucleus],"[{'label': 'chest wall', 'ontology_term_id': '...",HTAPP-213-SMP-6752 scRNA-seq,False,PUBLIC,None,None

## Optimize the amount of data we load from S3

* `select_row_groups_ilp` picks the minimum set of row groups to get the required cell type counts from a parquet file.  It uses an Integer Linear Programming solver to find an optimal solution quickly
* use `s3fs` to access only portions of `s3` objects that are needed to read the rows and columns needed
* use `arrow` to efficiently access specific portions of the parquet file without loading the entire file

In [24]:
import pulp

def select_row_groups_ilp(cell_type_counts_per_row_group, needed):
  """
  cell_type_counts_per_row_group: list of dicts, one per row group, mapping cell_type to count
  needed: dict mapping cell_type to required count
  Returns: set of row group indices to read
  """
  n_row_groups = len(cell_type_counts_per_row_group)
  cell_types = list(needed.keys())

  # Define the problem
  prob = pulp.LpProblem("RowGroupSelection", pulp.LpMinimize)

  # Binary variables: x_r = 1 if row group r is selected
  x = [pulp.LpVariable(f"x_{r}", cat="Binary") for r in range(n_row_groups)]

  # Objective: minimize number of row groups
  prob += pulp.lpSum(x)

  # Constraints: for each cell type, enough cells must be selected
  for c in cell_types:
    prob += (
      pulp.lpSum(
        cell_type_counts_per_row_group[r].get(c, 0) * x[r]
        for r in range(n_row_groups)
      ) >= needed[c],
      f"cover_{c}"
    )

  # Solve
  prob.solve()

  # Extract selected row groups
  selected = {r for r in range(n_row_groups) if pulp.value(x[r]) > 0.5}
  return selected

In [25]:
# Test case 1: Simple, non-overlapping
cell_type_counts_per_row_group_1 = [
  {'A': 10},   # row group 0
  {'B': 10},   # row group 1
  {'C': 10},   # row group 2
]
needed_1 = {'A': 5, 'B': 5, 'C': 5}
print("Test 1 selected row groups:", select_row_groups_ilp(cell_type_counts_per_row_group_1, needed_1))
# Expected: {0, 1, 2}

# Test case 2: Overlapping, can use fewer row groups
cell_type_counts_per_row_group_2 = [
  {'A': 5, 'B': 5},   # row group 0
  {'B': 5, 'C': 5},   # row group 1
  {'A': 5, 'C': 5},   # row group 2
]
needed_2 = {'A': 5, 'B': 5, 'C': 5}
print("Test 2 selected row groups:", select_row_groups_ilp(cell_type_counts_per_row_group_2, needed_2))
# Expected: Any two row groups, e.g., {0,1}, {0,2}, or {1,2}

# Test case 3: Need more than one row group for a cell type
cell_type_counts_per_row_group_3 = [
  {'A': 3},   # row group 0
  {'A': 2, 'B': 5},   # row group 1
  {'B': 5, 'C': 5},   # row group 2
]
needed_3 = {'A': 5, 'B': 5}
print("Test 3 selected row groups:", select_row_groups_ilp(cell_type_counts_per_row_group_3, needed_3))
# Expected: {0,1} (for A), and either 1 or 2 for B, so {0,1}, {0,2}, or {0,1,2}

# Test case 4: Impossible to satisfy
cell_type_counts_per_row_group_4 = [
  {'A': 2},   # row group 0
  {'B': 2},   # row group 1
]
needed_4 = {'A': 5, 'B': 5}
print("Test 4 selected row groups:", select_row_groups_ilp(cell_type_counts_per_row_group_4, needed_4))
# Expected: set(), or infeasible (no solution)

# Test case 5: Redundant row group
cell_type_counts_per_row_group_5 = [
  {'A': 5, 'B': 5},   # row group 0
  {'A': 5},           # row group 1
  {'B': 5},           # row group 2
]
needed_5 = {'A': 5, 'B': 5}
print("Test 5 selected row groups:", select_row_groups_ilp(cell_type_counts_per_row_group_5, needed_5))
# Expected: {0}

Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/a86a7294a9f7412aab543c5a1b47ace8-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/a86a7294a9f7412aab543c5a1b47ace8-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 8 COLUMNS
At line 21 RHS
At line 25 BOUNDS
At line 29 ENDATA
Problem MODEL has 3 rows, 3 columns and 3 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 1.5 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 3 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                3.00000000
Enumerated nodes:               0
Total iterations:               3
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Test 1 selected row groups: {0, 1, 2}
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/b109e6d99d584d6999313ae72d575b66-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/b109e6d99d584d6999313ae72d575b66-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 8 COLUMNS
At line 24 RHS
At line 28 BOUNDS
At line 32 ENDATA
Problem MODEL has 3 rows, 3 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 1.5 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 1 rows, 2 columns (2 integer (1 of which binary)) and 2 elements
Cutoff increment increased from 1e-05 to 0.9999
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of 2
Cbc0038I Before mini branch and bound, 2 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of 2 - took 0.00 seconds
Cbc0012I Integer solution of 2 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective 2, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from 2 to 2
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Test 2 selected row groups: {0, 2}
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/d72c40afac4d45f3b8e5e79f9970609f-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/d72c40afac4d45f3b8e5e79f9970609f-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 21 RHS
At line 24 BOUNDS
At line 28 ENDATA
Problem MODEL has 2 rows, 3 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 2 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Test 3 selected row groups: {0, 1}
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/d7bcd31c31f64d30889bf0fca43d0ca2-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/d7bcd31c31f64d30889bf0fca43d0ca2-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 16 RHS
At line 19 BOUNDS
At line 22 ENDATA
Problem MODEL has 2 rows, 2 columns and 2 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Problem is infeasible - 0.00 seconds
Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Test 4 selected row groups: {0, 1}
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/2bf45fb7f6c14bc483ac6df81d1b38df-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/2bf45fb7f6c14bc483ac6df81d1b38df-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 21 RHS
At line 24 BOUNDS
At line 28 ENDATA
Problem MODEL has 2 rows, 3 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 1 - 0.00 seconds
Cgl0004I processed model has 2 rows, 3 columns (3 integer (3 of which binary)) and 4 elements
Cutoff increment increased from 1e-05 to 0.9999
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of 1
Cbc0038I Before mini branch and bound, 3 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of 1 - took 0.00 seconds
Cbc0012I Integer solution of 1 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective 1, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from 1 to 1
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Test 5 selected row groups: {0}

In [26]:
import pyarrow as pa
import pyarrow.parquet as pq
import pandas as pd
import tqdm
import s3fs
from collections import defaultdict
import pyarrow.compute as pc
import numpy as np

fs = s3fs.S3FileSystem(anon=False, profile='xcellerate')


def optimized_row_group_sample_arrow(counts_df: pd.DataFrame, parquet_path: str) -> pd.DataFrame:
  """
  Efficiently sample rows for each cell type by first scanning row groups for relevant cell types and their counts,
  then only reading the minimal set of row groups needed to fulfill the sample requirements.
  Uses Arrow for filtering to minimize memory usage.
  """
  needed = {
    row['cell_type']: row['cell_count']
    for _, row in counts_df.iterrows()
  }
  collected = {cell_type: [] for cell_type in needed}
  done = set()

  print(f"Opening {parquet_path}")
  with (
    fs.open(parquet_path, 'rb')
    if parquet_path[:5] == "s3://"
    else open(parquet_path, 'rb')
  ) as f:
    parquet_file = pq.ParquetFile(f)
    n_row_groups = parquet_file.num_row_groups
    print(f"Found {n_row_groups} row groups")

    if n_row_groups > 1:
      # First pass: build a list of dicts with cell type counts for each row group
      print("Indexing row groups for cell types and counts...")
      cell_type_counts_per_row_group = []
      for rg_idx in tqdm.tqdm(range(n_row_groups)):
        table = parquet_file.read_row_group(
          rg_idx,
          columns=['cell_type', 'assay', 'organism']
        )
        # Arrow filtering
        assay_str = pc.cast(table['assay'], pa.string())
        organism_str = pc.cast(table['organism'], pa.string())
        assay_mask = pc.starts_with(assay_str, '10x')
        organism_mask = pc.equal(organism_str, 'Homo sapiens')
        combined_mask = pc.and_(assay_mask, organism_mask)
        filtered_table = table.filter(combined_mask)
        counts = filtered_table['cell_type'].to_pandas().value_counts().to_dict()
        cell_type_counts_per_row_group.append(counts)
        del table, filtered_table

      # Use ILP to select the optimal set of row groups
      print("Selecting optimal row groups using ILP...")
      row_groups_to_read = select_row_groups_ilp(cell_type_counts_per_row_group, needed)
      del cell_type_counts_per_row_group
      row_groups_to_read = sorted(row_groups_to_read)
    else:
      row_groups_to_read = [ 0 ]

    # Second pass: read only the needed row groups, and sample for each cell type
    print(f"Reading {len(row_groups_to_read)} row groups ...")
    for rg_idx in tqdm.tqdm(row_groups_to_read):
      print("reading row group", rg_idx)
      num_rows = parquet_file.metadata.row_group(rg_idx).num_rows
      print("num rows", num_rows)
      table = parquet_file.read_row_group(
        rg_idx,
        columns=['cell_type', 'assay', 'organism'] + [
          col for col in parquet_file.schema.names
          if col not in ['cell_type', 'assay', 'organism']
        ]
      )

      print("filtering")

      # Arrow filtering
      assay_str = pc.cast(table['assay'], pa.string())
      organism_str = pc.cast(table['organism'], pa.string())
      assay_mask = pc.starts_with(assay_str, '10x')
      organism_mask = pc.equal(organism_str, 'Homo sapiens')
      combined_mask = pc.and_(assay_mask, organism_mask)
      filtered_table = table.filter(combined_mask)
      del table

      # For each cell type still needing samples and present in this row group
      for cell_type in needed:
        if cell_type in done:
          continue
        print("filtering for cell type", cell_type)
        cell_type_mask = pc.equal(filtered_table['cell_type'], cell_type)
        subset_table = filtered_table.filter(cell_type_mask)
        n_needed = needed[cell_type] - sum(len(x) for x in collected[cell_type])
        if n_needed <= 0:
          done.add(cell_type)
          continue
        if subset_table.num_rows > 0:
          n_sample = min(n_needed, subset_table.num_rows)
          # Sample indices in Arrow, then convert only the sample to pandas
          indices = np.random.choice(subset_table.num_rows, n_sample, replace=False)
          sampled_table = subset_table.take(indices)
          sampled_df = sampled_table.to_pandas()
          collected[cell_type].append(sampled_df)
          if n_sample == n_needed:
            done.add(cell_type)
        del subset_table
      # Stop early if all cell types are done
      if len(done) == len(needed):
        print(f"All cell types are done")
        break

  # Concatenate all collected samples
  all_samples = [pd.concat(collected[cell_type], ignore_index=True) for cell_type in collected if collected[cell_type]]
  return pd.concat(all_samples, ignore_index=True)

### Review and example optimization

In [27]:

human_only_x10_metadata_pdf.iloc[741].filename

's3://cdiam-h5ad-database/cellxgene_v2/ff4cfa86-9c0c-4b7c-abd6-90547657d04f'

In [28]:
from pathlib import Path

index = 741
filename = Path(human_only_x10_metadata_pdf.iloc[index].filename).stem
embedding_path = f"s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/{filename}.parquet"

example_training_embeddings_pdf = optimized_row_group_sample_arrow(training_counts_pdf[training_counts_pdf["index"] == index], embedding_path)
example_training_embeddings_pdf.cell_type.value_counts()

Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ff4cfa86-9c0c-4b7c-abd6-90547657d04f.parquet
Found 1 row groups
Reading 1 row groups ...

  0%|          | 0/1 [00:00<?, ?it/s]

reading row group 0
num rows 9799
filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type T cell
filtering for cell type malignant cell
filtering for cell type blood vessel endothelial cell
filtering for cell type blood vessel smooth muscle cell
filtering for cell type cell of skeletal muscle

  0%|          | 0/1 [00:04<?, ?it/s]

All cell types are done

cell_type
cell of skeletal muscle            1578
malignant cell                      750
blood vessel endothelial cell       536
T cell                              173
macrophage                          134
fibroblast                           68
blood vessel smooth muscle cell       6
Name: count, dtype: int64

In [29]:
training_counts_pdf[training_counts_pdf["index"] == 741]

     index                        cell_type  cell_count
180    741                       fibroblast          68
75     741                       macrophage         134
63     741                           T cell         173
14     741                   malignant cell         750
23     741    blood vessel endothelial cell         536
6      741  blood vessel smooth muscle cell           6
2      741          cell of skeletal muscle        1578

In [30]:
from pathlib import Path

for index, group in training_counts_pdf.groupby('index'):
  filename = Path(human_only_x10_metadata_pdf.iloc[index].filename)
  print(filename)
  print(group)
  break

s3:/cdiam-h5ad-database/cellxgene_v2/00476f9f-ebc1-4b72-b541-32f912ce36ea
   index                               cell_type  cell_count
0      0                                  neuron          68
0      0                         oligodendrocyte          75
0      0                              fibroblast          25
0      0                        endothelial cell          16
0      0                               astrocyte          81
0      0          oligodendrocyte precursor cell          79
0      0                                pericyte           9
0      0       central nervous system macrophage          94
0      0  vascular associated smooth muscle cell          11
0      0                               leukocyte           3
0      0                          ependymal cell          27

## Ok, GO!

Extact the embeddings from the training set and write them to a local directory

In [32]:
import s3fs
import tqdm
from dataclasses import dataclass

@dataclass
class EmbeddingFetchError:
  index: int
  file_path: str
  error: Exception
  group: pd.DataFrame

import json

error_log_path = data_dir / "cellxgene_embeddings" / "training_v1" / "embedding_errors.log"
with open(error_log_path, "a") as error_log:
  fs = s3fs.S3FileSystem(anon=False, profile='xcellerate')
  for index, group in tqdm.tqdm(training_counts_pdf.groupby('index')):
    filename = Path(human_only_x10_metadata_pdf.iloc[index].filename).stem
    file_size = human_only_x10_metadata_pdf.iloc[index].file_size

    print(f"Processing {filename} with size {file_size}")
    
    embedding_path = f"s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/{filename}.parquet"
    
    output_path = data_dir / "cellxgene_embeddings" / "training_v1" / f"{filename}.parquet"
    if output_path.exists():
      continue

    try:
      training_embeddings_pdf = optimized_row_group_sample_arrow(
        training_counts_pdf[training_counts_pdf["index"] == index],
        embedding_path
      )
      training_embeddings_pdf.to_parquet(output_path)
      del training_embeddings_pdf
    except Exception as e:
      efe = EmbeddingFetchError(index, embedding_path, e, group)
      # Write error info as JSON (convert group to string for simplicity)
      error_log.write(json.dumps({
        "index": efe.index,
        "file_path": efe.file_path,
        "error": str(efe.error),
        "group": efe.group.reset_index(drop=True).to_json()  # or str(efe.group)
      }) + "\n")
      error_log.flush()  # Ensure it's written immediately
      print(efe)

  0%|          | 0/642 [00:00<?, ?it/s]

 55%|█████▌    | 354/642 [00:00<00:00, 3537.75it/s]

Processing 00476f9f-ebc1-4b72-b541-32f912ce36ea with size 750437761
Processing 0087cde2-967d-4f7c-8e6e-40e4c9ad1891 with size 389395627
Processing 00e5dedd-b9b7-43be-8c28-b0e5c6414a62 with size 705366728
Processing 00ff600e-6e2e-4d76-846f-0eec4f0ae417 with size 7187747
Processing 01209dce-3575-4bed-b1df-129f57fbc031 with size 801497925
Processing 0129dbd9-a7d3-4f6b-96b9-1da155a93748 with size 9828162445
Processing 019c7af2-c827-4454-9970-44d5e39ce068 with size 491650252
Processing 01ad3cd7-3929-4654-84c0-6db05bd5fd59 with size 12326224885
Processing 01c93cf6-b695-4e30-a26e-121ae8b16a9e with size 119252466
Processing 030faa69-ff79-4d85-8630-7c874a114c19 with size 2983375726
Processing 03181d87-4769-41e7-8c39-d9a81835f0d2 with size 4697014766
Processing 0325478a-9b52-45b5-b40a-2e2ab0d72eb1 with size 38214116935
Processing 0374f03c-62e2-4859-8a14-acb00b0627d5 with size 1043486165
Processing 03c544fb-a103-4d18-9230-eae9cfee3af2 with size 926053492
Processing 03d38670-1444-4001-bc53-9936e61d9b20 with size 927518499
Processing 03d5794d-cde9-4769-a1a9-b3899d2b1d87 with size 100729743
Processing 04a23820-ffa8-4be5-9f65-64db15631d1e with size 3778257186
Processing 04b0eb97-d816-44bb-93a5-8b2968791aa0 with size 100575445
Processing 04c0bdd8-840f-488e-b72d-2a1229bc65db with size 737380068
Processing 04c94a7d-1133-42c9-bb48-c697bd302a8d with size 9318231388
Processing 04d87de6-c20a-4186-8884-f47dba20b0a4 with size 34219993
Processing 059022cf-885a-4ef8-944b-d9e5381aa1c6 with size 5918172358
Processing 05a49baa-d326-42ae-86d2-94de3a659901 with size 106964446
Processing 066943a2-fdac-4b29-b348-40cede398e4e with size 15370858912
Processing 06b91002-4d3d-4d2e-8484-20c3b31e232c with size 54147722
Processing 07428d73-fdea-4bd4-a801-94b00c4d961c with size 273372802
Processing 07760522-707a-4a1c-8891-dbd1226d6b27 with size 1350619891
Processing 077b0429-0f47-48e0-879a-39eaae531d42 with size 643588106
Processing 07854d9c-5375-4a9b-ac34-fa919d3c3686 with size 4303213798
Processing 07b1d7c8-5c2e-42f7-9246-26f746cd6013 with size 1107832765
Processing 08073b32-d389-41f4-a4fd-616de76915ab with size 430829532
Processing 0895c838-e550-48a3-a777-dbcd35d30272 with size 4683005
Processing 090da8ea-46e8-40df-bffc-1f78e1538d27 with size 835379978
Processing 095940cb-7422-4510-96e2-cbafd961eb88 with size 1763708869
Processing 0a21f80c-e7a3-465b-8aba-fdda2b4c36bc with size 2090892307
Processing 0a2d7e87-c3c0-4ed2-86df-ae18811fcc16 with size 1761406852
Processing 0b4a15a7-4e9e-4555-9733-2423e5c66469 with size 945952549
Processing 0b75c598-0893-4216-afe8-5414cab7739d with size 7093524299
Processing 0ba16f4b-cb87-4fa3-9363-19fc51eec6e7 with size 212676439
Processing 0ba636a1-4754-4786-a8be-7ab3cf760fd6 with size 21986922694
Processing 0bc7235a-ae5a-479d-a487-510435377e55 with size 6845724367
Processing 0c774045-26a7-40f8-9b07-6742d3c771c0 with size 4740914134
Processing 0c86f0de-ddcb-454c-b00b-37feb69e7da1 with size 42336479
Processing 0c9a8cfb-6649-4d52-b418-6d8e56bd7afe with size 19966593
Processing 0caedec7-1c7d-4e79-aba2-50f6916e643f with size 6695826857
Processing 0d7f4c06-a6bd-47d2-a42b-3a7196704f77 with size 219999236
Processing 0de831e0-a525-4ec5-b717-df56f2de2bf0 with size 422597339
Processing 0eccaf0c-19d2-4900-9962-899378adf8be with size 763623304
Processing 0ed60482-a34f-4268-b576-d69cc30210f6 with size 3720670959
Processing 0ee5ae70-c3f5-473f-bd1c-287f4690ffc5 with size 362056970
Processing 0f4865d5-8000-4f68-8ac7-f5efea9e5e70 with size 706588192
Processing 0fdb6122-4600-40f0-a703-2da47cc7080d with size 166425475
Processing 1009f384-b12d-448e-ba9f-1b7d2ecfbb4e with size 43851563
Processing 100c6145-7b0e-4ba6-81c1-ffebed0d1ac4 with size 1485656703
Processing 105c7dad-0468-4628-a5be-2bb42c6a8ae4 with size 572308944
Processing 1062c0f2-2a44-4cf9-a7c8-b5ed58b4728d with size 1858562701
Processing 1185a7d3-a9c1-4280-9ba5-d61895b15cac with size 2683199531
Processing 1196334f-a441-474a-95ee-400780941690 with size 1100312626
Processing 11a3244a-6b2f-43ca-95a5-d2cd95c482d2 with size 254902173
Processing 11ef37ee-2173-458e-aab8-7fe35da8e47b with size 282356645
Processing 11ff73e8-d3e4-4445-9309-477a2c5be6f6 with size 2197567584
Processing 12194ced-8086-458e-84a8-e2ab935d8db1 with size 583456487
Processing 124744b8-4681-474a-9894-683896122708 with size 245496908
Processing 1252c5fb-945f-42d6-b1a8-8a3bd864384b with size 768297969
Processing 12c3efd8-d515-42e6-b93c-4961e599d524 with size 782447845
Processing 12c868c6-94df-48b5-acf2-b82f6aa14074 with size 323857731
Processing 137ca42b-33b3-48fa-ae80-02a0747027cb with size 426947052
Processing 14363b6e-3428-45b0-8704-10fd5d6316df with size 234976036
Processing 146216e1-ec30-4fee-a1fb-25defe801e2d with size 3344190894
Processing 1492eb6b-7d50-4c4d-94ac-c801a7d5555c with size 156894141
Processing 149b2c3f-ee11-47a7-984b-923570280bd7 with size 14443987
Processing 15e0ec3e-a05f-4cd8-8624-96448f5a2b58 with size 583089301
Processing 171b03c9-516b-499c-a434-fa4f70191988 with size 535842362
Processing 182f6a56-7360-4924-a74e-1772e07b3031 with size 2033694074
Processing 18500fcd-9960-49cb-8a8e-7d868dc14efe with size 2274075802
Processing 1851b6ab-2386-40a1-8c2a-b7cd895b889e with size 515793294
Processing 1884e651-5f7f-4e6c-a71a-843ba272aaf4 with size 121702305
Processing 18e2a8c5-33f7-455e-a58a-b2ba6921db27 with size 7759299329
Processing 19b21f40-db42-4a71-a0d6-913e83b17784 with size 2230758849
Processing 1a018108-b4b6-457b-ba15-046d5e98c169 with size 667457239
Processing 1a2e3350-28a8-4f49-b33c-5b67ceb001f6 with size 3101951059
Processing 1a38e762-2465-418f-b81c-6a4bce261c34 with size 16281994466
Processing 1a434263-2aa5-4fd9-a1f3-1c4a2a8fb771 with size 669469672
Processing 1a7e99fe-d5b6-44d7-aa50-c6ef6ab29761 with size 277737017
Processing 1a974af7-8b4b-4abb-8aba-23e2979d9518 with size 1344855717
Processing 1b52ee22-c71a-4a0f-a4d2-c1be36d0b82a with size 20593790837
Processing 1b767f95-d0a0-4a3d-b394-cc665d86c3dc with size 2312826497
Processing 1b9d8702-5af8-4142-85ed-020eb06ec4f6 with size 8239115096
Processing 1c05b7ae-4dfb-4c1b-a441-4b23c04b169e with size 1638181148
Processing 1c739a3e-c3f5-49d5-98e0-73975e751201 with size 5097929975
Processing 1c9f5c6b-73da-4d17-95de-df080ffe0df1 with size 1415343385
Processing 1cf24082-59de-4029-ac81-6e398768af3a with size 2126265135
Processing 1e5bd3b8-6a0e-4959-8d69-cafed30fe814 with size 905256158
Processing 1f1c5c14-5949-4c81-b28e-b272e271b672 with size 252028819
Processing 1fc48734-35ee-4372-885c-95fd2674c75a with size 5930026245
Processing 20980d73-7c53-4039-b852-b76a01566d5a with size 2158862808
Processing 20d87640-4be8-487f-93d4-dce38378d00f with size 111880398
Processing 214bf9eb-93db-48c8-8e3c-9bb22fa3bc63 with size 175285440
Processing 2185eb07-22e2-4209-b3c8-7111afc6aa90 with size 3654651283
Processing 218acb0f-9f2f-4f76-b90b-15a4b7c7f629 with size 12876398501
Processing 2190bd4d-3be0-4bf7-8ca8-8d6f71228936 with size 8548208254
Processing 21d3e683-80a4-4d9b-bc89-ebb2df513dde with size 4601159236
Processing 22658f4f-9268-41ad-8828-cc53f4baa9fa with size 946649753
Processing 234c23d0-d6cd-4612-a40d-e5811727564b with size 881565566
Processing 236baeda-5fdd-41bf-8e32-bae21ac7d435 with size 154454055
Processing 24066994-8183-488d-b037-ef6bb524af39 with size 146046525
Processing 248cf7bf-508b-4c28-a2fd-cabe2ab956aa with size 159227437
Processing 24ec2dc5-3573-4d66-a9e1-25b7dcf43e27 with size 352645168
Processing 251b1a7e-d050-4486-8d50-4c2619eb0f46 with size 6782121506
Processing 2672b679-8048-4f5e-9786-f1b196ccfd08 with size 1110705342
Processing 2727d83a-0af0-443a-bff8-58dc7028289a with size 586394697
Processing 27d91086-cfe3-4e33-9282-bd1246e5ce8e with size 3384425644
Processing 2856d06c-0ff9-4e01-bfc9-202b74d0b60f with size 1730968627
Processing 2872f4b0-b171-46e2-abc6-befcf6de6306 with size 746184936
Processing 290d50c7-7158-4198-acf5-6d4b624fd3dc with size 535882208
Processing 2a498ace-872a-4935-984b-1afa70fd9886 with size 7256147879
Processing 2a65bd41-4a3f-42f4-98b2-c53962811152 with size 225646831
Processing 2a7f90de-098a-4a6f-ac07-9e6462792412 with size 7390056988
Processing 2a8ca8f3-5599-4cda-b973-3a2dfc3c1fe6 with size 943645855
Processing 2aa1c93c-4ef3-4e9a-98e7-0bd37933953c with size 6680216306
Processing 2d31c0ca-0233-41ce-bd1a-05aa8404b073 with size 151185284
Processing 2dd73feb-0527-47d5-8c7b-35b6de16aecb with size 133644548
Processing 2e5a9b5d-d31b-4e9f-a179-d5d70ba459fb with size 177552307
Processing 2e9d2f32-4cfb-49b5-b990-cbf4c241214e with size 1079234841
Processing 2ecc72f8-085f-4e86-8692-771f316c54f6 with size 88673798
Processing 2f132ec9-24b5-422f-9be0-ccef03b4fe28 with size 956010044
Processing 2f6a20f1-173d-4b8d-860b-c47ffea120fa with size 37144501
Processing 2f7230e7-4706-4924-b571-473fc1e52c30 with size 157736674
Processing 2fc9c59f-3cfd-48d9-9b23-e369ea31bff3 with size 93945742
Processing 305c1196-76b3-42d1-818f-2694d01dbd97 with size 87450099
Processing 3079e9b0-c6db-45c8-b998-a4555a73968e with size 1563142581
Processing 30cd5311-6c09-46c9-94f1-71fe4b91813c with size 2602445257
Processing 30f5e171-83d7-4fc0-bf75-384f122346b3 with size 30596265
Processing 31285bcd-9a28-48ce-8cc0-543af80261d3 with size 363156499
Processing 31f04740-c712-4c4b-a3f8-55c0506b3034 with size 2778663378
Processing 3294d050-6eeb-4a00-b24c-71aacc9b777f with size 1094746744
Processing 32b9bdce-2481-4c85-ba1b-6ad5fcea844c with size 2310579995
Processing 33911db3-f461-464b-8083-a397ab616a09 with size 427872265
Processing 34229bdc-a895-4394-8820-574e4028d8c6 with size 2411892928
Processing 343ff97c-85df-494b-8400-beb937618611 with size 291091507
Processing 34deb33b-a50e-4993-a38b-1c0e5079c1c2 with size 2507348754
Processing 35090826-f636-40c1-a3ef-4466beeab9f8 with size 1561868384
Processing 359f7af4-87d4-4117-9d6c-ca4cfa1f3f0b with size 2502128045
Processing 35c8a04c-8639-4d15-8228-765d8d93fc96 with size 1087790861
Processing 364348b4-bc34-4fe1-a851-60d99e36cafa with size 669937706
Processing 367b55f4-d543-49aa-90e8-4765fcb8c687 with size 1920916503
Processing 36c867a7-be10-4e69-9b39-5de12b0af6da with size 312608018
Processing 37b21763-7f0f-41ae-9001-60bad6e2841d with size 2312081143
Processing 381aa407-317a-40ef-8048-7ce0eacc4266 with size 1038362753
Processing 38491c97-ce53-43d6-b34a-ef93176c9481 with size 645667033
Processing 389bfbb9-8ef1-4582-8c41-410131c3d0eb with size 1368917228
Processing 390b376d-8857-4b4b-991f-0d7326938172 with size 192933484
Processing 3966ba97-beb8-4d0b-9954-d3775cd2cd61 with size 9683636863
Processing 396a9124-fb20-4822-bf9c-e93fdf7c999a with size 214370769
Processing 39f6fec9-2539-4b99-982b-f12888ef649a with size 472701671
Processing 3a1df9df-425e-451f-9d69-1ba7985296d9 with size 903060877
Processing 3a7f3ab4-a280-4b3b-b2c0-6dd05614a78c with size 21619090403
Processing 3affa268-8a74-460a-ac9b-a984c0832469 with size 6510796878
Processing 3b6ed41e-10a1-47dd-b995-8cde7d041fd6 with size 45330028
Processing 3b8b5de4-3aa1-4ac6-8890-8d03c8219981 with size 5380959669
Processing 3c75a463-6a87-4132-83a8-c3002624394d with size 1905704933
Processing 3d044b52-140a-4528-bf0d-a2dbef9e1f40 with size 123378112
Processing 3d0d6923-a2c4-476f-a53e-3b7bfa010d90 with size 5657178153
Processing 3dc61ca1-ce40-46b6-8337-f27260fd9a03 with size 2600594920
Processing 3de0ad6d-4378-4f62-b37b-ec0b75a50d94 with size 943957862
Processing 3e4e2c8e-cd17-4ece-9141-1e7f4ce8da1f with size 273536117
Processing 3e87b1fa-472a-401c-8fa8-f31c10437d5f with size 66215847
Processing 3f31f8ce-bbf6-4df8-8203-aa240ed03026 with size 2685424807
Processing 3f32121d-126b-4e8d-9f69-d86502d2a1b1 with size 1071391585
Processing 3f56901c-dd4a-47d6-b60b-7b0c0111cfb2 with size 2295936016
Processing 3faad104-2ab8-4434-816d-474d8d2641db with size 16323494970
Processing 4023a2bc-6325-47db-bfdf-9639e91042c2 with size 3645743574
Processing 40318d39-3d8f-49f4-8455-a2e1365c5c5b with size 2480315543
Processing 40569510-2282-461b-84df-6218ef208e0e with size 1031532016
Processing 40e79234-65e8-45e9-b555-5c663154a108 with size 13747131130
Processing 421e5f54-5de7-425f-b399-34ead0651ce1 with size 3051109583
Processing 4269074c-f2c1-4d88-b2c3-0946f59d5449 with size 48322495
Processing 42b6a476-c51d-4f8b-b68b-44941b3a11bf with size 310109222
Processing 43245158-5ae1-4e71-a9a6-67eef49c26bc with size 5086770288
Processing 43b7e156-65b3-4a7b-8c7a-08528e4b21d0 with size 2593501326
Processing 44882825-0da1-4547-b721-2c6105d4a9d1 with size 671245965
Processing 44941fdb-8a6f-42d5-9b34-da48c2a3f774 with size 44662634
Processing 44c83972-e5d2-4858-ac58-2df9f4bf564b with size 10358166074
Processing 44c93f2b-dd66-4d15-81ef-de9394c76290 with size 9082998728
Processing 4593c820-512d-4805-a10f-c0b864a7cc8c with size 2440193580
Processing 460dfe21-0550-4521-92fe-db0f3036d8b0 with size 485233949
Processing 46ff9dc2-3d87-4b36-91aa-ffa8aa13c52e with size 2835231283
Processing 470565f2-5afc-456a-b617-18e4496c04fd with size 164001151
Processing 471647b3-04fe-4c76-8372-3264feb950e8 with size 1105181307
Processing 4724c395-0c46-46d2-81f7-60fd271fb488 with size 1957107562
Processing 48101fa2-1a63-4514-b892-53ea1d3a8657 with size 17473604128
Processing 482954b2-0456-4901-b379-b62f99c0ab2d with size 559399998
Processing 4859642c-d155-437b-adf5-83ca6c1bef67 with size 16697406
Processing 486486d4-9462-43e5-9249-eb43fa5a49a6 with size 757132558
Processing 489318a0-24c3-4f5c-b105-f084ed0ea026 with size 489687644
Processing 489eaa11-c119-4a5f-b44b-81e33c80c0ef with size 2472850269
Processing 48c4a72a-bc2a-4d7c-9146-a7c2ab1d7d9f with size 4601791861
Processing 492d9f77-c4c8-485d-92d7-7686fe6c8482 with size 202952445
Processing 4976b234-9028-4b4b-8a2f-8ac59d636219 with size 2391788868
Processing 4993d61c-1d04-4630-9c61-8d9431f39adc with size 22356756
Processing 49dbdcb6-f1d5-4423-9999-1e4a6b67d10b with size 412556883
Processing 4b6af54a-4a21-46e0-bc8d-673c0561a836 with size 711293850
Processing 4c4cd77c-8fee-4836-9145-16562a8782fe with size 1164416702
Processing 4c6f9f26-5470-455b-8933-c408232fbf56 with size 86888953
Processing 4cdd25a4-f4fa-4c13-b8a9-80cf28511d46 with size 482645391
Processing 4ce8d8ec-b94c-4b79-afcb-b094336d8a78 with size 140487011
Processing 4d2e0563-cf4a-48bd-aa7f-efc26025b53a with size 591865594
Processing 4d43082e-59cd-43ac-b77d-54d55519c881 with size 1659257722
Processing 4dd00779-7f73-4f50-89bb-e2d3c6b71b18 with size 564356344
Processing 4dd1cd23-fc4d-4fd1-9709-602540f3ca6f with size 601867025
Processing 4e374783-0152-423e-bcb6-b87cc232f64d with size 1234312139
Processing 4e38f019-f8e8-44ae-ad32-ba500de6f64c with size 400374169
Processing 4e74d843-8d7a-497a-918a-f079ef141b6d with size 153976559
Processing 4ebcbeeb-2208-4d30-acb2-8142a5201814 with size 336826717
Processing 4ed927e9-c099-49af-b8ce-a2652d069333 with size 2841376585
Processing 4fb330ab-2d74-4649-b58f-7ffef457efdf with size 6218988239
Processing 5097d77d-08fa-4105-a18f-4072d61522a4 with size 3484273996
Processing 50dc91a1-36b6-472a-b884-7307b6961ab1 with size 259195007
Processing 50eb1e23-b8d4-4f76-a184-44e5541fa05a with size 107219548
Processing 518d9049-2a76-44f8-8abc-1e2b59ab5ba1 with size 1553691871
Processing 51d9716c-50bb-4fd8-8d1e-7d9329969cb7 with size 770839300
Processing 51f476f7-b24d-42f3-8871-7dab3fa35e96 with size 97975575
Processing 524d4513-8afd-4120-9b7b-fe31ae10c29b with size 169416417
Processing 524e045e-e74c-4e00-9884-d5c3bef3d862 with size 20826845
Processing 529bb209-9d7b-44da-bfa4-f6e4745c46c2 with size 2727569914
Processing 52ea546e-9229-40ef-b048-a2e694dd73e8 with size 4345144559
Processing 52f18bc3-52d9-487b-bf8f-f0b7aa684b09 with size 2331926697
Processing 531c9543-9093-45ed-93ac-ebc5815bfb8a with size 223073269
Processing 5346f9c6-755e-4336-94cc-38706ec00c2f with size 2725088603
Processing 535e9336-2d8d-43c3-944d-bcbebe20df8a with size 3679688884
Processing 53bc5729-6202-4351-bc99-1f36139e9dc4 with size 6801175402
Processing 5467c340-864c-4810-86ef-647039c07148 with size 609879154
Processing 54d56674-e4e1-4e3c-9110-ea5cc2ac0eb5 with size 366372284
Processing 5500c673-1610-40a0-86d9-64d987ae50e6 with size 1173536764
Processing 551ad2bc-2e82-4541-8aab-849988d43752 with size 1177618965
Processing 55ca4411-8c7d-4aef-a572-50852e030c05 with size 549609597
Processing 56c33a38-2732-4e53-a9c1-1bc61eda9a99 with size 3038072838
Processing 572f3f3e-d3e4-4d13-8e2b-88215e508481 with size 2603112866
Processing 574e9f9e-f8b4-41ef-bf19-89a9964fd9c7 with size 2434279378
Processing 576f193c-75d0-4a11-bd25-8676587e6dc2 with size 4024690429
Processing 5829c7ba-697f-418e-8b98-d605b192dc48 with size 6222348006
Processing 58679288-9ecc-4647-9781-12a3a8f8c6fd with size 67430640
Processing 58c43cc2-e00e-43c4-94eb-8501369264e1 with size 1402661434
Processing 595c9010-99ec-462d-b6a1-2b2fe5407871 with size 537750211
Processing 598100f7-01da-4de4-998a-05917fd6c446 with size 21438121470
Processing 59923449-e303-43e6-9e63-03ef92f5ebd1 with size 1797409535
Processing 599504e5-d4ad-45bd-9128-823faf0fb9c9 with size 1580909198
Processing 59b69042-47c2-47fd-ad03-d21beb99818f with size 1368671010
Processing 5a73f63f-18a2-49b5-b431-2c469c41a41b with size 1775640001
Processing 5ae6ab72-1927-4d5b-9826-86be65791293 with size 1263716000
Processing 5b9b89d2-2e3e-4ad1-8965-666f64540fea with size 15073845554
Processing 5ba85070-a41c-4184-9c18-cf34c3fd0f62 with size 299390246
Processing 5bc23cb2-8cfc-4960-bab1-c3027fbeefc4 with size 2207394337
Processing 5cdbb2ea-c622-466d-9ead-7884ad8cb99f with size 329914296
Processing 5ce42b38-d867-487f-9b40-e8bb00b21d0b with size 1767890347
Processing 5e5ab909-f73f-4b57-98a0-6d2c5662f6a4 with size 1967926980
Processing 5e717147-0f75-4de1-8bd2-6fda01b8d75f with size 1917143398
Processing 5e7fff82-b8eb-4220-bf65-c6feb6765ea1 with size 31941460
Processing 5f4556b6-017e-49b3-b31c-c6e8e226c9fb with size 169921960
Processing 605b89b1-c474-4180-8c0b-88afb5920991 with size 12085015327
Processing 62315937-e268-4fa5-a032-8f7d776f3a3f with size 114320053
Processing 62de80d7-e6c4-4ff0-ad4c-d3d36f57cb93 with size 46009578
Processing 639ffc23-14db-4060-9027-3c90314200f8 with size 2606825123
Processing 63bb6359-3945-4658-92eb-3072419953e4 with size 151835453
Processing 6437bc9c-16cb-46c8-8f79-9a7384a0212a with size 5075152931
Processing 644a578d-ffdc-446b-9679-e7ab4c919c13 with size 1204517574
Processing 646e3e87-e46b-4b12-85b5-8d8589e26088 with size 33466566217
Processing 64767efb-49b0-4562-a1bd-e619a5d9db41 with size 1181347686
Processing 64f4ad90-a422-400a-944d-4ce0f39594a7 with size 2091408287
Processing 6538ce1b-7949-405f-b01c-a2c3e876baee with size 4503210739
Processing 65badd7a-9262-4fd1-9ce2-eb5dc0ca8039 with size 17940200093
Processing 6701d782-76f2-40e6-82f1-495350dd9a63 with size 45666627
Processing 675873e1-3f1d-4bd5-9fad-3ce8a5ad98e1 with size 16275234231
Processing 6929d6d1-6f81-44d7-bd35-5a580259af81 with size 82539808
Processing 693ae928-96ba-47de-b9d9-1321c675bfcd with size 482387730
Processing 6a30bf44-c490-41ac-965b-0bb58432b10a with size 1623155613
Processing 6c105286-54e3-4587-969f-30683390ff8c with size 6226084511
Processing 6c600df6-ddca-4628-a8bb-1d6de1e3f9b4 with size 1194671433
Processing 6cda07c7-5d7a-41ba-9799-5bb73da25a60 with size 490365337
Processing 6cda3b13-7257-45b9-ac20-0a7e6697e4f2 with size 1083258843
Processing 6cf3634d-e911-44ad-bf52-c747a9af3c01 with size 510148828
Processing 6dafb698-7a53-4699-ad13-1b5e2c164be7 with size 211330907
Processing 6ed0bb6c-a9e3-4ba6-9436-7c8fd4e206f0 with size 2962875780
Processing 700aed19-c16e-4ba8-9191-07da098a8626 with size 1849738462
Processing 703f00e6-b996-48e5-bc34-00c41b9876f4 with size 18488827
Processing 70e4f35b-c98c-45a1-9aa9-2053b07315dd with size 2235629272
Processing 715327a6-7978-4896-ba91-69d6b04dbbfb with size 2445784472
Processing 71be997d-ff75-41b9-8a9f-1288c865f921 with size 1342622051
Processing 72822932-10f6-466f-baf3-a2c1d89364bc with size 648335049
Processing 731e6380-879f-4b0b-9a1f-2150208852ef with size 58267828
Processing 7357bdd2-e05b-4e87-acd9-e3a26382648b with size 895743850
Processing 73b7d0aa-035f-4a15-9f1d-f56b70204591 with size 121702654

100%|██████████| 28/28 [00:27<00:00,  1.00it/s]t/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/93c3d18d78fa4806bea0514bbf7ae713-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/93c3d18d78fa4806bea0514bbf7ae713-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 23 COLUMNS
At line 612 RHS
At line 631 BOUNDS
At line 660 ENDATA
Problem MODEL has 18 rows, 28 columns and 504 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 28 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 28 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                28.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 28 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type L2/3-6 intratelencephalic projecting glutamatergic neuron
filtering for cell type oligodendrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type microglial cell
filtering for cell type pvalb GABAergic cortical interneuron
filtering for cell type VIP GABAergic cortical interneuron
filtering for cell type sst GABAergic cortical interneuron
filtering for cell type lamp5 GABAergic cortical interneuron
filtering for cell type astrocyte of the cerebral cortex
filtering for cell type corticothalamic-projecting glutamatergic cortical neuron
filtering for cell type L6b glutamatergic cortical neuron
filtering for cell type sncg GABAergic cortical interneuron
filtering for cell type near-projecting glutamatergic cortical neuron
filtering for cell type chandelier pvalb GABAergic cortical interneuron
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type caudal ganglionic eminence derived interneuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 1
num rows 50000
filtering
filtering for cell type corticothalamic-projecting glutamatergic cortical neuron
filtering for cell type L6b glutamatergic cortical neuron
filtering for cell type sncg GABAergic cortical interneuron
filtering for cell type near-projecting glutamatergic cortical neuron
filtering for cell type chandelier pvalb GABAergic cortical interneuron
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type caudal ganglionic eminence derived interneuron

filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell
reading row group 2
num rows 50000
filtering
filtering for cell type corticothalamic-projecting glutamatergic cortical neuron
filtering for cell type L6b glutamatergic cortical neuron
filtering for cell type sncg GABAergic cortical interneuron
filtering for cell type near-projecting glutamatergic cortical neuron
filtering for cell type chandelier pvalb GABAergic cortical interneuron
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type caudal ganglionic eminence derived interneuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 3
num rows 50000
filtering
filtering for cell type corticothalamic-projecting glutamatergic cortical neuron
filtering for cell type L6b glutamatergic cortical neuron
filtering for cell type chandelier pvalb GABAergic cortical interneuron
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type caudal ganglionic eminence derived interneuron
filtering for cell type vascular leptomeningeal cell

filtering for cell type cerebral cortex endothelial cell
reading row group 4
num rows 50000
filtering
filtering for cell type chandelier pvalb GABAergic cortical interneuron
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type caudal ganglionic eminence derived interneuron

filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell
reading row group 5
num rows 50000
filtering
filtering for cell type chandelier pvalb GABAergic cortical interneuron
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type caudal ganglionic eminence derived interneuron

filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell
reading row group 6
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 7
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 8
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 9
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron

filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell
reading row group 10
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 11
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 12
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 13
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron

filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell
reading row group 14
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 15
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type vascular leptomeningeal cell
filtering for cell type cerebral cortex endothelial cell

reading row group 16
num rows 50000
filtering

filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type cerebral cortex endothelial cell
reading row group 17
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type cerebral cortex endothelial cell

reading row group 18
num rows 50000
filtering

filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type cerebral cortex endothelial cell
reading row group 19
num rows 50000
filtering

filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type cerebral cortex endothelial cell
reading row group 20
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron

filtering for cell type cerebral cortex endothelial cell
reading row group 21
num rows 50000
filtering

filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type cerebral cortex endothelial cell
reading row group 22
num rows 50000
filtering

filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type cerebral cortex endothelial cell
reading row group 23
num rows 50000
filtering

filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type cerebral cortex endothelial cell
reading row group 24
num rows 50000
filtering
filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron

filtering for cell type cerebral cortex endothelial cell
reading row group 25
num rows 50000
filtering

filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
filtering for cell type cerebral cortex endothelial cell
reading row group 26
num rows 50000
filtering

filtering for cell type cerebral cortex endothelial cell
reading row group 27
num rows 28211
filtering

 96%|█████████▋| 27/28 [11:35<00:25, 25.75s/it]

filtering for cell type cerebral cortex endothelial cell
All cell types are done

 74%|███████▎  | 472/642 [12:11<05:39,  2.00s/it]

Processing c2a461b1-0c15-4047-9fcb-1f966fe55100 with size 1854544731
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c2a461b1-0c15-4047-9fcb-1f966fe55100.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 97499
filtering
filtering for cell type T cell
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type naive thymus-derived CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive monocyte
filtering for cell type CD16-positive, CD56-dim natural killer cell, human
filtering for cell type naive B cell
filtering for cell type erythrocyte
filtering for cell type plasma cell
filtering for cell type naive thymus-derived CD8-positive, alpha-beta T cell
filtering for cell type memory B cell
filtering for cell type regulatory T cell
filtering for cell type CD8-positive, alpha-beta memory T cell
filtering for cell type neutrophil
filtering for cell type gamma-delta T cell
filtering for cell type mature NK T cell
filtering for cell type conventional dendritic cell
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type mucosal invariant T cell
filtering for cell type CD14-low, CD16-positive monocyte
filtering for cell type CD16-negative, CD56-bright natural killer cell, human
filtering for cell type plasmacytoid dendritic cell
filtering for cell type platelet
filtering for cell type plasmablast

  0%|          | 0/1 [01:04<?, ?it/s]

filtering for cell type hematopoietic stem cell
filtering for cell type immature B cell
All cell types are done

 74%|███████▎  | 473/642 [13:20<06:21,  2.26s/it]

Processing c2aad8fc-b63b-4f9b-9cfd-baf7bc9c1771 with size 3221661309
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c2aad8fc-b63b-4f9b-9cfd-baf7bc9c1771.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 37642
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:18<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 74%|███████▍  | 474/642 [13:39<06:35,  2.35s/it]

Processing c3aa4f95-7a18-4a7d-8dd8-ca324d714363 with size 49667672749
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c3aa4f95-7a18-4a7d-8dd8-ca324d714363.parquet
Found 13 row groups
Indexing row groups for cell types and counts...

100%|██████████| 13/13 [00:15<00:00,  1.17s/it]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/f1b22a91e35a4bfaaaed4ddc2e8e3da6-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/f1b22a91e35a4bfaaaed4ddc2e8e3da6-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 59 RHS
At line 61 BOUNDS
At line 75 ENDATA
Problem MODEL has 1 rows, 13 columns and 13 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.01176 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 12
num rows 38941
filtering
filtering for cell type L2/3-6 intratelencephalic projecting glutamatergic neuron

  0%|          | 0/1 [00:16<?, ?it/s]

All cell types are done

 74%|███████▍  | 475/642 [14:12<07:13,  2.60s/it]

Processing c3d381b2-3104-444e-8ad5-d3524407bbb6 with size 48444733
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c3d381b2-3104-444e-8ad5-d3524407bbb6.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 1875

  0%|          | 0/1 [00:01<?, ?it/s]

filtering
filtering for cell type retina horizontal cell
All cell types are done

 74%|███████▍  | 476/642 [14:14<07:09,  2.59s/it]

Processing c3fe3c1e-5bf8-4678-b74a-79899243ad41 with size 552857860
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c3fe3c1e-5bf8-4678-b74a-79899243ad41.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 28702

 74%|███████▍  | 476/642 [14:29<07:09,  2.59s/it]

filtering
filtering for cell type secretory cell
filtering for cell type basal cell of prostate epithelium
filtering for cell type luminal cell of prostate epithelium
filtering for cell type leukocyte
filtering for cell type epithelial cell of urethra
filtering for cell type prostate gland microvascular endothelial cell
filtering for cell type neuroendocrine cell
filtering for cell type smooth muscle cell of prostate
filtering for cell type fibroblast of connective tissue of prostate

  0%|          | 0/1 [00:16<?, ?it/s]

All cell types are done

 74%|███████▍  | 477/642 [14:35<07:52,  2.87s/it]

Processing c42c8ad3-9761-49e5-b9bf-ee8ebd50416f with size 143811607
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c42c8ad3-9761-49e5-b9bf-ee8ebd50416f.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 4154
filtering
filtering for cell type gut endothelial cell

  0%|          | 0/1 [00:02<?, ?it/s]

All cell types are done

 74%|███████▍  | 478/642 [14:39<07:53,  2.89s/it]

Processing c4b03352-af8d-492a-8d6b-40f304e0a122 with size 12482520433
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c4b03352-af8d-492a-8d6b-40f304e0a122.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 152189

 74%|███████▍  | 478/642 [14:49<07:53,  2.89s/it]

filtering
filtering for cell type neuron

  0%|          | 0/1 [01:33<?, ?it/s]

All cell types are done

 75%|███████▍  | 479/642 [16:13<15:19,  5.64s/it]

Processing c4dd26a8-d956-4bee-a233-44b573f2ce27 with size 1241030703
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c4dd26a8-d956-4bee-a233-44b573f2ce27.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 11265
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:06<?, ?it/s]

filtering for cell type ependymal cell
All cell types are done

 75%|███████▍  | 480/642 [16:20<15:25,  5.71s/it]

Processing c52de62a-058d-4d78-a464-bdf552378f43 with size 285143643
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c52de62a-058d-4d78-a464-bdf552378f43.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 8345
filtering
filtering for cell type neuron
filtering for cell type fibroblast
filtering for cell type mesenchymal stem cell

  0%|          | 0/1 [00:05<?, ?it/s]

filtering for cell type myofibroblast cell
All cell types are done

Processing c5cfa2b7-abb1-4a50-908f-707b54ca606b with size 664113442
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c5cfa2b7-abb1-4a50-908f-707b54ca606b.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 14094
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte
filtering for cell type ependymal cell

  0%|          | 0/1 [00:08<?, ?it/s]

All cell types are done

Processing c6413315-7158-46c5-a5fd-7228385694f1 with size 2052013788
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c6413315-7158-46c5-a5fd-7228385694f1.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.33it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/7c169de5b6404e65ab0b8c772e3bbf73-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/7c169de5b6404e65ab0b8c772e3bbf73-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 17 COLUMNS
At line 48 RHS
At line 61 BOUNDS
At line 64 ENDATA
Problem MODEL has 12 rows, 2 columns and 24 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.916226 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               1
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 0
num rows 50000

 75%|███████▍  | 480/642 [16:40<15:25,  5.71s/it]

filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type B cell
filtering for cell type pericyte
filtering for cell type blood vessel endothelial cell
filtering for cell type mast cell
filtering for cell type mature NK T cell
filtering for cell type secretory cell
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type smooth muscle cell
filtering for cell type myofibroblast cell

  0%|          | 0/1 [00:22<?, ?it/s]

filtering for cell type ciliated epithelial cell
All cell types are done

 75%|███████▌  | 483/642 [17:02<18:28,  6.97s/it]

Processing c69fb6cd-fc4d-4216-85cb-8d80e7771786 with size 460950795
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c69fb6cd-fc4d-4216-85cb-8d80e7771786.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 10224
filtering
filtering for cell type epithelial cell of lung
filtering for cell type multi-ciliated epithelial cell
filtering for cell type basal cell of epithelium of bronchus
filtering for cell type lung secretory cell
filtering for cell type respiratory suprabasal cell
filtering for cell type squamous epithelial cell

  0%|          | 0/1 [00:04<?, ?it/s]

filtering for cell type bronchial goblet cell
All cell types are done

 75%|███████▌  | 484/642 [17:10<18:30,  7.03s/it]

Processing c76098ba-eed3-45b1-98f2-96fcac55ed18 with size 1429306271
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c76098ba-eed3-45b1-98f2-96fcac55ed18.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 40000
filtering
filtering for cell type microglial cell

  0%|          | 0/1 [00:17<?, ?it/s]

All cell types are done

Processing c7775e88-49bf-4ba2-a03b-93f00447c958 with size 13771561054
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c7775e88-49bf-4ba2-a03b-93f00447c958.parquet
Found 13 row groups
Indexing row groups for cell types and counts...

100%|██████████| 13/13 [00:16<00:00,  1.25s/it]t]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/450482a3f615471bba0ad8ca6f065719-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/450482a3f615471bba0ad8ca6f065719-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 49 COLUMNS
At line 634 RHS
At line 679 BOUNDS
At line 693 ENDATA
Problem MODEL has 44 rows, 13 columns and 545 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 13 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 13 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                13.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 13 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type malignant cell
filtering for cell type naive thymus-derived CD4-positive, alpha-beta T cell
filtering for cell type monocyte
filtering for cell type central memory CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive monocyte
filtering for cell type effector memory CD8-positive, alpha-beta T cell
filtering for cell type CD16-positive, CD56-dim natural killer cell, human
filtering for cell type naive B cell
filtering for cell type erythrocyte
filtering for cell type naive thymus-derived CD8-positive, alpha-beta T cell
filtering for cell type regulatory T cell
filtering for cell type gamma-delta T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type mature NK T cell
filtering for cell type dendritic cell
filtering for cell type mucosal invariant T cell
filtering for cell type effector CD8-positive, alpha-beta T cell
filtering for cell type CD14-low, CD16-positive monocyte
filtering for cell type CD16-negative, CD56-bright natural killer cell, human
filtering for cell type plasmacytoid dendritic cell
filtering for cell type T follicular helper cell
filtering for cell type megakaryocyte
filtering for cell type IgA plasma cell
filtering for cell type platelet
filtering for cell type plasmablast
filtering for cell type class switched memory B cell
filtering for cell type immature B cell
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type IgG plasma cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian
filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human

reading row group 1
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type malignant cell
filtering for cell type monocyte
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type dendritic cell
filtering for cell type mucosal invariant T cell
filtering for cell type CD14-low, CD16-positive monocyte
filtering for cell type T follicular helper cell
filtering for cell type megakaryocyte
filtering for cell type IgA plasma cell
filtering for cell type plasmablast
filtering for cell type class switched memory B cell
filtering for cell type immature B cell
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type IgG plasma cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian

filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human
reading row group 2
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type malignant cell
filtering for cell type monocyte
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type dendritic cell
filtering for cell type CD14-low, CD16-positive monocyte
filtering for cell type T follicular helper cell
filtering for cell type megakaryocyte
filtering for cell type IgA plasma cell
filtering for cell type class switched memory B cell
filtering for cell type immature B cell
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type IgG plasma cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian
filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human

reading row group 3
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type malignant cell
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type dendritic cell
filtering for cell type CD14-low, CD16-positive monocyte
filtering for cell type megakaryocyte
filtering for cell type IgA plasma cell
filtering for cell type class switched memory B cell
filtering for cell type immature B cell
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type IgG plasma cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian

filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human
reading row group 4
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type malignant cell
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type dendritic cell
filtering for cell type CD14-low, CD16-positive monocyte
filtering for cell type megakaryocyte
filtering for cell type IgA plasma cell
filtering for cell type class switched memory B cell
filtering for cell type immature B cell
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type IgG plasma cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian
filtering for cell type myeloid lineage restricted progenitor cell

filtering for cell type ILC1, human
reading row group 5
num rows 50000
filtering
filtering for cell type malignant cell
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type megakaryocyte
filtering for cell type IgA plasma cell
filtering for cell type class switched memory B cell
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type IgG plasma cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell

filtering for cell type erythroid progenitor cell, mammalian
filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human
reading row group 6
num rows 50000
filtering
filtering for cell type malignant cell
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type megakaryocyte
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type IgG plasma cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell

filtering for cell type erythroid progenitor cell, mammalian
filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human
reading row group 7
num rows 50000
filtering
filtering for cell type malignant cell
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type megakaryocyte
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian
filtering for cell type myeloid lineage restricted progenitor cell

filtering for cell type ILC1, human
reading row group 8
num rows 50000
filtering
filtering for cell type malignant cell
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type megakaryocyte
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian

filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human
reading row group 9
num rows 50000
filtering
filtering for cell type malignant cell
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type megakaryocyte
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type T-helper 22 cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian
filtering for cell type myeloid lineage restricted progenitor cell

filtering for cell type ILC1, human
reading row group 10
num rows 50000
filtering
filtering for cell type malignant cell
filtering for cell type erythrocyte
filtering for cell type regulatory T cell
filtering for cell type megakaryocyte
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian

filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human
reading row group 11
num rows 50000
filtering
filtering for cell type malignant cell
filtering for cell type regulatory T cell
filtering for cell type megakaryocyte
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian

filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human
reading row group 12
num rows 47366
filtering
filtering for cell type malignant cell
filtering for cell type regulatory T cell
filtering for cell type unswitched memory B cell
filtering for cell type T-helper 17 cell
filtering for cell type myeloid dendritic cell
filtering for cell type hematopoietic precursor cell
filtering for cell type dendritic cell, human
filtering for cell type T-helper 1 cell
filtering for cell type IgM plasma cell
filtering for cell type CD34-positive, CD38-negative hematopoietic stem cell
filtering for cell type erythroid progenitor cell, mammalian
filtering for cell type myeloid lineage restricted progenitor cell
filtering for cell type ILC1, human

 92%|█████████▏| 12/13 [05:16<00:26, 26.41s/it]

All cell types are done

 76%|███████▌  | 486/642 [23:18<1:31:56, 35.36s/it]

Processing c7856243-c59a-4b70-8ce7-25b94c2d9da1 with size 1409779998
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c7856243-c59a-4b70-8ce7-25b94c2d9da1.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 14352
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:06<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 76%|███████▌  | 487/642 [23:25<1:23:57, 32.50s/it]

Processing c7d0def0-2dcd-4111-902b-67e6baeac119 with size 309738266
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c7d0def0-2dcd-4111-902b-67e6baeac119.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 10918
filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type T cell
filtering for cell type malignant cell
filtering for cell type blood vessel endothelial cell
filtering for cell type hepatocyte
filtering for cell type blood vessel smooth muscle cell
filtering for cell type hepatic stellate cell
filtering for cell type endothelial cell of hepatic sinusoid

  0%|          | 0/1 [00:05<?, ?it/s]

All cell types are done

Processing c874f155-9bf9-4928-b821-f52c876b3e48 with size 130789344
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c874f155-9bf9-4928-b821-f52c876b3e48.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 4603
filtering
filtering for cell type B cell
filtering for cell type plasma cell
filtering for cell type myeloid cell
filtering for cell type neutrophil
filtering for cell type mature NK T cell
filtering for cell type dendritic cell

  0%|          | 0/1 [00:02<?, ?it/s]

filtering for cell type platelet
All cell types are done

Processing c8d40d53-387b-48f2-9f89-72bfdb9c7c9f with size 1010104086
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c8d40d53-387b-48f2-9f89-72bfdb9c7c9f.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:00<00:00,  2.05it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/56dfb20ea24842c28e2eb669d17f5fac-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/56dfb20ea24842c28e2eb669d17f5fac-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 7 COLUMNS
At line 18 RHS
At line 21 BOUNDS
At line 24 ENDATA
Problem MODEL has 2 rows, 2 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.0205881 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 0
num rows 50000

 76%|███████▌  | 487/642 [23:40<1:23:57, 32.50s/it]

filtering
filtering for cell type pericyte

  0%|          | 0/1 [00:23<?, ?it/s]

filtering for cell type vascular associated smooth muscle cell
All cell types are done

 76%|███████▋  | 490/642 [24:01<1:06:12, 26.14s/it]

Processing c8f83821-a242-4ed7-86e9-7da077f5d348 with size 64771360
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/c8f83821-a242-4ed7-86e9-7da077f5d348.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 3596

  0%|          | 0/1 [00:01<?, ?it/s]

filtering
filtering for cell type astrocyte
filtering for cell type ependymal cell
All cell types are done

 76%|███████▋  | 491/642 [24:03<58:13, 23.14s/it]

Processing ca20e2ac-5676-4158-b5d0-0c2b15898b19 with size 701853733
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ca20e2ac-5676-4158-b5d0-0c2b15898b19.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 33968
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:15<?, ?it/s]

All cell types are done

Processing cab0bc48-744c-461b-aaf4-7bf2cb7af00d with size 106244346
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/cab0bc48-744c-461b-aaf4-7bf2cb7af00d.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 5080

 76%|███████▋  | 491/642 [24:20<58:13, 23.14s/it]

filtering
filtering for cell type B cell
filtering for cell type erythrocyte
filtering for cell type plasma cell

  0%|          | 0/1 [00:02<?, ?it/s]

filtering for cell type myeloid cell
filtering for cell type mature NK T cell
filtering for cell type dendritic cell
All cell types are done

 77%|███████▋  | 493/642 [24:22<48:27, 19.51s/it]

Processing cac02b79-9f54-4668-9235-60d3b76a4197 with size 680025457
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/cac02b79-9f54-4668-9235-60d3b76a4197.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 14285
filtering
filtering for cell type secretory cell

  0%|          | 0/1 [00:06<?, ?it/s]

All cell types are done

 77%|███████▋  | 494/642 [24:29<43:06, 17.48s/it]

Processing caf8670f-e647-4f0c-bfba-163aa84ce602 with size 7029130343
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/caf8670f-e647-4f0c-bfba-163aa84ce602.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.22it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/f6b9070d81314ec1b37fa6bdd0ed5b4d-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/f6b9070d81314ec1b37fa6bdd0ed5b4d-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 15 RHS
At line 17 BOUNDS
At line 20 ENDATA
Problem MODEL has 1 rows, 2 columns and 2 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.00132 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 0
num rows 50000

 77%|███████▋  | 494/642 [24:40<43:06, 17.48s/it]

filtering
filtering for cell type neuron

  0%|          | 0/1 [00:23<?, ?it/s]

All cell types are done

 77%|███████▋  | 495/642 [24:54<46:21, 18.92s/it]

Processing ccfdcad0-7104-46b9-addf-fd66a2a15907 with size 759169797
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ccfdcad0-7104-46b9-addf-fd66a2a15907.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 34723
filtering
filtering for cell type fibroblast
filtering for cell type T cell
filtering for cell type natural killer cell
filtering for cell type astrocyte
filtering for cell type monocyte
filtering for cell type microglial cell
filtering for cell type pericyte
filtering for cell type retinal rod cell
filtering for cell type retinal ganglion cell
filtering for cell type rod bipolar cell
filtering for cell type mast cell
filtering for cell type amacrine cell
filtering for cell type Mueller cell
filtering for cell type endothelial cell of vascular tree
filtering for cell type ON-bipolar cell
filtering for cell type retinal cone cell
filtering for cell type OFF-bipolar cell
filtering for cell type melanocyte
filtering for cell type retina horizontal cell

  0%|          | 0/1 [00:17<?, ?it/s]

filtering for cell type retinal pigment epithelial cell
All cell types are done

 77%|███████▋  | 496/642 [25:15<47:06, 19.36s/it]

Processing cd6398a9-c0af-4467-9091-c536866535bd with size 274435969
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/cd6398a9-c0af-4467-9091-c536866535bd.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 10016
filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type malignant cell
filtering for cell type endothelial cell
filtering for cell type monocyte
filtering for cell type blood vessel endothelial cell
filtering for cell type mature NK T cell

  0%|          | 0/1 [00:04<?, ?it/s]

filtering for cell type blood vessel smooth muscle cell
All cell types are done

 77%|███████▋  | 497/642 [25:21<39:21, 16.28s/it]

Processing cd77258f-b08b-4c89-b93f-6e6f146b1a4d with size 225468890
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/cd77258f-b08b-4c89-b93f-6e6f146b1a4d.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 8362
filtering
filtering for cell type glutamatergic neuron

  0%|          | 0/1 [00:04<?, ?it/s]

All cell types are done

Processing cda2c8cd-be1c-42e5-b2cd-162caa1c4ce7 with size 7153814285
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/cda2c8cd-be1c-42e5-b2cd-162caa1c4ce7.parquet
Found 6 row groups
Indexing row groups for cell types and counts...

100%|██████████| 6/6 [00:06<00:00,  1.08s/it]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/842af1007a1d435ebb3cfd2f9ead4cb2-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/842af1007a1d435ebb3cfd2f9ead4cb2-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 38 COLUMNS
At line 248 RHS
At line 282 BOUNDS
At line 289 ENDATA
Problem MODEL has 33 rows, 6 columns and 191 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 6 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 6 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                6.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 6 row groups ...

reading row group 0
num rows 50000

 77%|███████▋  | 497/642 [25:40<39:21, 16.28s/it]

filtering
filtering for cell type fibroblast
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type macrophage
filtering for cell type T cell
filtering for cell type natural killer cell
filtering for cell type endothelial cell
filtering for cell type monocyte
filtering for cell type naive B cell
filtering for cell type erythrocyte
filtering for cell type plasma cell
filtering for cell type memory B cell
filtering for cell type double-positive, alpha-beta thymocyte
filtering for cell type regulatory T cell
filtering for cell type CD8-positive, alpha-beta memory T cell
filtering for cell type double negative thymocyte
filtering for cell type gamma-delta T cell
filtering for cell type mast cell
filtering for cell type dendritic cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type lymphocyte
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type plasmacytoid dendritic cell
filtering for cell type progenitor cell
filtering for cell type megakaryocyte
filtering for cell type precursor B cell
filtering for cell type alpha-beta T cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell
filtering for cell type cortical thymic epithelial cell
filtering for cell type medullary thymic epithelial cell

filtering for cell type early T lineage precursor
filtering for cell type epithelial cell of thymus
reading row group 1
num rows 50000
filtering
filtering for cell type monocyte
filtering for cell type naive B cell
filtering for cell type erythrocyte
filtering for cell type plasma cell
filtering for cell type memory B cell
filtering for cell type CD8-positive, alpha-beta memory T cell
filtering for cell type mast cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type lymphocyte
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type plasmacytoid dendritic cell
filtering for cell type progenitor cell
filtering for cell type megakaryocyte
filtering for cell type precursor B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell
filtering for cell type cortical thymic epithelial cell
filtering for cell type medullary thymic epithelial cell
filtering for cell type early T lineage precursor

filtering for cell type epithelial cell of thymus
reading row group 2
num rows 50000
filtering
filtering for cell type monocyte
filtering for cell type erythrocyte
filtering for cell type plasma cell
filtering for cell type CD8-positive, alpha-beta memory T cell
filtering for cell type mast cell
filtering for cell type lymphocyte
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type progenitor cell
filtering for cell type megakaryocyte
filtering for cell type precursor B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell
filtering for cell type cortical thymic epithelial cell
filtering for cell type medullary thymic epithelial cell
filtering for cell type early T lineage precursor
filtering for cell type epithelial cell of thymus

reading row group 3
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type mast cell
filtering for cell type lymphocyte
filtering for cell type progenitor cell
filtering for cell type megakaryocyte
filtering for cell type precursor B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type cortical thymic epithelial cell
filtering for cell type medullary thymic epithelial cell
filtering for cell type early T lineage precursor
filtering for cell type epithelial cell of thymus

reading row group 4
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type mast cell
filtering for cell type lymphocyte
filtering for cell type progenitor cell
filtering for cell type megakaryocyte
filtering for cell type precursor B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type cortical thymic epithelial cell
filtering for cell type medullary thymic epithelial cell
filtering for cell type early T lineage precursor

filtering for cell type epithelial cell of thymus
reading row group 5
num rows 5901
filtering
filtering for cell type mast cell
filtering for cell type lymphocyte
filtering for cell type progenitor cell
filtering for cell type precursor B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type early T lineage precursor
filtering for cell type epithelial cell of thymus

 83%|████████▎ | 5/6 [02:01<00:24, 24.37s/it]

All cell types are done

 78%|███████▊  | 499/642 [27:41<1:29:41, 37.64s/it]

Processing cdefb878-7f00-4b9d-9eda-b3652cfac0c8 with size 68857674
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/cdefb878-7f00-4b9d-9eda-b3652cfac0c8.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 1641

  0%|          | 0/1 [00:00<?, ?it/s]

filtering
filtering for cell type lung ciliated cell
All cell types are done

 78%|███████▊  | 500/642 [27:43<1:10:19, 29.72s/it]

Processing ce009dc1-ac57-4386-b72f-5c575701c253 with size 48441273
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ce009dc1-ac57-4386-b72f-5c575701c253.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 2834
filtering
filtering for cell type B cell
filtering for cell type epithelial cell
filtering for cell type myeloid cell

  0%|          | 0/1 [00:01<?, ?it/s]

filtering for cell type neutrophil
filtering for cell type mature NK T cell
filtering for cell type ionocyte
All cell types are done

Processing cec9f9a5-8832-437d-99af-fb8237cde54b with size 82926256
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/cec9f9a5-8832-437d-99af-fb8237cde54b.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 1777
filtering
filtering for cell type retinal ganglion cell
filtering for cell type OFF retinal ganglion cell
filtering for cell type ON retinal ganglion cell

  0%|          | 0/1 [00:01<?, ?it/s]

All cell types are done

Processing cfa3c355-ee77-4fc8-9a00-78e61d23024c with size 105289854
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/cfa3c355-ee77-4fc8-9a00-78e61d23024c.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 4355

  0%|          | 0/1 [00:02<?, ?it/s]

filtering
filtering for cell type endothelial cell of lymphatic vessel
All cell types are done

Processing cfa755c1-48c5-4336-94f4-aa95eca4fbd5 with size 442463789
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/cfa755c1-48c5-4336-94f4-aa95eca4fbd5.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 7689

  0%|          | 0/1 [00:03<?, ?it/s]

filtering
filtering for cell type choroid plexus epithelial cell
All cell types are done

Processing d01c9dff-abd1-4825-bf30-2eb2ba74597e with size 7529214585
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d01c9dff-abd1-4825-bf30-2eb2ba74597e.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 92969

 78%|███████▊  | 500/642 [28:00<1:10:19, 29.72s/it]

filtering
filtering for cell type corticothalamic-projecting glutamatergic cortical neuron
filtering for cell type L6b glutamatergic cortical neuron
filtering for cell type near-projecting glutamatergic cortical neuron

  0%|          | 0/1 [00:58<?, ?it/s]

filtering for cell type L5 extratelencephalic projecting glutamatergic cortical neuron
All cell types are done

 79%|███████▊  | 505/642 [28:57<46:53, 20.53s/it]

Processing d02287f3-408b-438d-9131-999e460cbd0e with size 2773890551
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d02287f3-408b-438d-9131-999e460cbd0e.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 36941
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage

  0%|          | 0/1 [00:24<?, ?it/s]

filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte
All cell types are done

 79%|███████▉  | 506/642 [29:22<48:05, 21.22s/it]

Processing d0c12af4-c0e4-4c7b-873a-70752b449689 with size 9294882803
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d0c12af4-c0e4-4c7b-873a-70752b449689.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 318656
filtering
filtering for cell type neuron
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type epithelial cell
filtering for cell type stromal cell
filtering for cell type smooth muscle cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type mesothelial cell
filtering for cell type hepatocyte
filtering for cell type keratinocyte
filtering for cell type myofibroblast cell
filtering for cell type glial cell
filtering for cell type chondrocyte
filtering for cell type melanocyte
filtering for cell type skeletal muscle satellite cell
filtering for cell type epithelial cell of nephron
filtering for cell type osteoblast
filtering for cell type enteroendocrine cell
filtering for cell type cell of skeletal muscle
filtering for cell type interstitial cell of Cajal
filtering for cell type eurydendroid cell

  0%|          | 0/1 [03:12<?, ?it/s]

All cell types are done

 79%|███████▉  | 507/642 [32:41<1:57:59, 52.44s/it]

Processing d0ea3ec4-0f3b-4649-9146-1c0b5f303a55 with size 1934361891
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d0ea3ec4-0f3b-4649-9146-1c0b5f303a55.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 18903
filtering
filtering for cell type L6b glutamatergic cortical neuron

  0%|          | 0/1 [00:12<?, ?it/s]

All cell types are done

 79%|███████▉  | 508/642 [32:55<1:39:42, 44.65s/it]

Processing d1cbed97-d88f-4954-8925-13302fe30b39 with size 538471703
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d1cbed97-d88f-4954-8925-13302fe30b39.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 15481
filtering
filtering for cell type fibroblast
filtering for cell type vascular associated smooth muscle cell
filtering for cell type hepatocyte
filtering for cell type endothelial cell of pericentral hepatic sinusoid
filtering for cell type hepatic stellate cell
filtering for cell type endothelial cell of hepatic sinusoid

  0%|          | 0/1 [00:09<?, ?it/s]

filtering for cell type endothelial cell of periportal hepatic sinusoid
filtering for cell type cholangiocyte
All cell types are done

 79%|███████▉  | 509/642 [33:06<1:22:35, 37.26s/it]

Processing d224c8e0-c28e-4360-9e42-b3977cd83f9f with size 188918677
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d224c8e0-c28e-4360-9e42-b3977cd83f9f.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 8030
filtering
filtering for cell type fibroblast
filtering for cell type endothelial cell

  0%|          | 0/1 [00:04<?, ?it/s]

filtering for cell type erythrocyte
All cell types are done

 79%|███████▉  | 510/642 [33:12<1:05:15, 29.66s/it]

Processing d2514440-d747-4d8d-b2c7-b58ef8b71fbe with size 2881924049
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d2514440-d747-4d8d-b2c7-b58ef8b71fbe.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 48856

 79%|███████▉  | 510/642 [33:30<1:05:15, 29.66s/it]

filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:32<?, ?it/s]

filtering for cell type choroid plexus epithelial cell
All cell types are done

 80%|███████▉  | 511/642 [33:45<1:06:42, 30.55s/it]

Processing d288b10a-643e-44bd-b451-96e9588b2ee5 with size 2744371650
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d288b10a-643e-44bd-b451-96e9588b2ee5.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 39053
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:14<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 80%|███████▉  | 512/642 [34:00<57:06, 26.35s/it]

Processing d2b5efc1-14c6-4b5f-bd98-40f9084872d7 with size 3053619720
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d2b5efc1-14c6-4b5f-bd98-40f9084872d7.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 36886
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:19<?, ?it/s]

filtering for cell type leukocyte
filtering for cell type ependymal cell
All cell types are done

 80%|███████▉  | 513/642 [34:20<53:05, 24.69s/it]

Processing d2fc9880-e6d3-4922-af5c-61f4f517adfa with size 3961240415
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d2fc9880-e6d3-4922-af5c-61f4f517adfa.parquet
Found 3 row groups
Indexing row groups for cell types and counts...

100%|██████████| 3/3 [00:02<00:00,  1.05it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/39ee81b6a4ac4f64a0f0e21e3274ffe8-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/39ee81b6a4ac4f64a0f0e21e3274ffe8-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 19 RHS
At line 21 BOUNDS
At line 25 ENDATA
Problem MODEL has 1 rows, 3 columns and 3 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.00148 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 2
num rows 11194

  0%|          | 0/1 [00:04<?, ?it/s]

filtering
filtering for cell type oligodendrocyte
All cell types are done

 80%|████████  | 514/642 [34:28<42:46, 20.05s/it]

Processing d319af7f-be2e-441e-8caa-3b8a88480e89 with size 849815639
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d319af7f-be2e-441e-8caa-3b8a88480e89.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 11404
filtering
filtering for cell type retinal ganglion cell

  0%|          | 0/1 [00:05<?, ?it/s]

All cell types are done

Processing d3a83885-5198-4b04-8314-b753b66ef9a8 with size 440990872
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d3a83885-5198-4b04-8314-b753b66ef9a8.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 19037

 80%|████████  | 514/642 [34:40<42:46, 20.05s/it]

filtering
filtering for cell type classical monocyte
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type plasma cell
filtering for cell type non-classical monocyte
filtering for cell type mature NK T cell
filtering for cell type dendritic cell
filtering for cell type effector CD8-positive, alpha-beta T cell
filtering for cell type CD1c-positive myeloid dendritic cell
filtering for cell type plasmacytoid dendritic cell
filtering for cell type granulocyte
filtering for cell type effector CD4-positive, alpha-beta T cell
filtering for cell type CD4-positive, alpha-beta thymocyte
filtering for cell type CD8-positive, alpha-beta thymocyte

  0%|          | 0/1 [00:10<?, ?it/s]

filtering for cell type CD141-positive myeloid dendritic cell
All cell types are done

 80%|████████  | 516/642 [34:49<32:54, 15.67s/it]

Processing d3d4baff-d142-4f13-acc6-96a4ef6a3e95 with size 176781142
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d3d4baff-d142-4f13-acc6-96a4ef6a3e95.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 6339
filtering
filtering for cell type endothelial cell
filtering for cell type pericyte
filtering for cell type leukocyte

  0%|          | 0/1 [00:02<?, ?it/s]

filtering for cell type stromal cell of ovary
All cell types are done

 81%|████████  | 517/642 [34:53<26:50, 12.88s/it]

Processing d41f45c1-1b7b-4573-a998-ac5c5acb1647 with size 1631749334
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d41f45c1-1b7b-4573-a998-ac5c5acb1647.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.34it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/c62ad69efde142ed9662dc452218f505-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/c62ad69efde142ed9662dc452218f505-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 13 COLUMNS
At line 36 RHS
At line 45 BOUNDS
At line 48 ENDATA
Problem MODEL has 8 rows, 2 columns and 16 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 2 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 2 row groups ...

reading row group 0
num rows 50000

 81%|████████  | 517/642 [35:10<26:50, 12.88s/it]

filtering
filtering for cell type fibroblast
filtering for cell type T cell
filtering for cell type B cell
filtering for cell type epithelial cell
filtering for cell type myeloid cell
filtering for cell type blood vessel endothelial cell

filtering for cell type neutrophil
filtering for cell type endothelial cell of lymphatic vessel
reading row group 1
num rows 32991
filtering
filtering for cell type endothelial cell of lymphatic vessel

 50%|█████     | 1/2 [00:40<00:40, 40.20s/it]

All cell types are done

/tmp/ipykernel_6603/4260646841.py:116: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_samples = [pd.concat(collected[cell_type], ignore_index=True) for cell_type in collected if collected[cell_type]]
 81%|████████  | 518/642 [35:36<42:35, 20.61s/it]

Processing d4cfefa0-3a35-44eb-b848-d7a725b481e7 with size 266116581
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d4cfefa0-3a35-44eb-b848-d7a725b481e7.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 9778
filtering
filtering for cell type epithelial cell
filtering for cell type basal cell
filtering for cell type hepatocyte
filtering for cell type club cell
filtering for cell type goblet cell
filtering for cell type epithelial cell of alveolus of lung
filtering for cell type ciliated epithelial cell
filtering for cell type neuroendocrine cell

  0%|          | 0/1 [00:05<?, ?it/s]

filtering for cell type ionocyte
filtering for cell type brush cell
All cell types are done

 81%|████████  | 519/642 [35:43<34:53, 17.02s/it]

Processing d4e69e01-3ba2-4d6b-a15d-e7048f78f22e with size 7824147517
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d4e69e01-3ba2-4d6b-a15d-e7048f78f22e.parquet
Found 10 row groups
Indexing row groups for cell types and counts...

100%|██████████| 10/10 [00:12<00:00,  1.26s/it]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/0c6209f253924fc5838f00be83935cb0-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/0c6209f253924fc5838f00be83935cb0-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 31 COLUMNS
At line 310 RHS
At line 337 BOUNDS
At line 348 ENDATA
Problem MODEL has 26 rows, 10 columns and 248 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 10 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 10 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                10.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 10 row groups ...

reading row group 0
num rows 50000

 81%|████████  | 519/642 [36:00<34:53, 17.02s/it]

filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type endothelial cell
filtering for cell type monocyte
filtering for cell type regular ventricular cardiac myocyte
filtering for cell type CD14-positive monocyte
filtering for cell type capillary endothelial cell
filtering for cell type neural cell
filtering for cell type pericyte
filtering for cell type vein endothelial cell
filtering for cell type endothelial cell of artery
filtering for cell type mast cell
filtering for cell type mature NK T cell
filtering for cell type dendritic cell
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type smooth muscle cell
filtering for cell type mesothelial cell
filtering for cell type regular atrial cardiac myocyte
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type activated CD8-positive, alpha-beta T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte
filtering for cell type epicardial adipocyte

reading row group 1
num rows 50000
filtering
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type monocyte
filtering for cell type CD14-positive monocyte
filtering for cell type neural cell
filtering for cell type vein endothelial cell
filtering for cell type mature NK T cell
filtering for cell type dendritic cell
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type mesothelial cell
filtering for cell type regular atrial cardiac myocyte
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type activated CD8-positive, alpha-beta T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte
filtering for cell type epicardial adipocyte

reading row group 2
num rows 50000
filtering
filtering for cell type monocyte
filtering for cell type CD14-positive monocyte
filtering for cell type neural cell
filtering for cell type mature NK T cell
filtering for cell type dendritic cell
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type mesothelial cell
filtering for cell type regular atrial cardiac myocyte
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type activated CD8-positive, alpha-beta T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte

filtering for cell type epicardial adipocyte
reading row group 3
num rows 50000
filtering
filtering for cell type CD14-positive monocyte
filtering for cell type dendritic cell
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type mesothelial cell
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte

filtering for cell type epicardial adipocyte
reading row group 4
num rows 50000
filtering
filtering for cell type CD14-positive monocyte
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type mesothelial cell
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte

filtering for cell type epicardial adipocyte
reading row group 5
num rows 50000
filtering
filtering for cell type CD14-positive monocyte
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type mesothelial cell
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte

filtering for cell type epicardial adipocyte
reading row group 6
num rows 50000
filtering
filtering for cell type CD14-positive monocyte
filtering for cell type mesothelial cell
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte

filtering for cell type epicardial adipocyte
reading row group 7
num rows 50000
filtering
filtering for cell type CD14-positive monocyte
filtering for cell type mesothelial cell
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte
filtering for cell type epicardial adipocyte

reading row group 8
num rows 50000
filtering
filtering for cell type CD14-positive monocyte

filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte
reading row group 9
num rows 36134
filtering
filtering for cell type CD14-positive monocyte
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte

 90%|█████████ | 9/10 [04:08<00:27, 27.57s/it]

All cell types are done

 81%|████████  | 520/642 [40:12<2:56:27, 86.79s/it]

Processing d5452b83-7c3d-4d7c-ab7a-c7fece7196c5 with size 574131170
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d5452b83-7c3d-4d7c-ab7a-c7fece7196c5.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 8077
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:04<?, ?it/s]

filtering for cell type ependymal cell
All cell types are done

 81%|████████  | 521/642 [40:17<2:08:12, 63.58s/it]

Processing d582f63a-3c88-4e38-8cd3-8682dbe40f64 with size 2473587202
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d582f63a-3c88-4e38-8cd3-8682dbe40f64.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 34919
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:17<?, ?it/s]

All cell types are done

 81%|████████▏ | 522/642 [40:35<1:40:41, 50.35s/it]

Processing d5a2d011-3765-4dad-ac36-3fff087589fe with size 459153914
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d5a2d011-3765-4dad-ac36-3fff087589fe.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 8093

  0%|          | 0/1 [00:03<?, ?it/s]

filtering
filtering for cell type lamp5 GABAergic cortical interneuron
All cell types are done

 81%|████████▏ | 523/642 [40:39<1:13:23, 37.00s/it]

Processing d5c67a4e-a8d9-456d-a273-fa01adb1b308 with size 427548254
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d5c67a4e-a8d9-456d-a273-fa01adb1b308.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 19694
filtering
filtering for cell type microglial cell
filtering for cell type retinal rod cell
filtering for cell type retinal ganglion cell
filtering for cell type amacrine cell
filtering for cell type Mueller cell
filtering for cell type ON-bipolar cell
filtering for cell type retinal cone cell
filtering for cell type OFF-bipolar cell

  0%|          | 0/1 [00:09<?, ?it/s]

All cell types are done

 82%|████████▏ | 524/642 [40:50<57:42, 29.34s/it]

Processing d6a5b240-cc8f-45c1-ad36-2fc291e15e8e with size 1847223560
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d6a5b240-cc8f-45c1-ad36-2fc291e15e8e.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 25875
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:13<?, ?it/s]

filtering for cell type leukocyte
filtering for cell type ependymal cell
All cell types are done

 82%|████████▏ | 525/642 [41:04<48:20, 24.79s/it]

Processing d7476ae2-e320-4703-8304-da5c42627e71 with size 5236107
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d7476ae2-e320-4703-8304-da5c42627e71.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 565
filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type T cell
filtering for cell type malignant cell
filtering for cell type endothelial cell
filtering for cell type monocyte
filtering for cell type hepatocyte

  0%|          | 0/1 [00:00<?, ?it/s]

All cell types are done

 82%|████████▏ | 526/642 [41:06<34:34, 17.88s/it]

Processing d7d7e89c-c93a-422d-8958-9b4a90b69558 with size 379935107
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d7d7e89c-c93a-422d-8958-9b4a90b69558.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 16901
filtering
filtering for cell type B cell
filtering for cell type naive thymus-derived CD4-positive, alpha-beta T cell
filtering for cell type CD16-positive, CD56-dim natural killer cell, human
filtering for cell type naive B cell
filtering for cell type myeloid cell
filtering for cell type naive thymus-derived CD8-positive, alpha-beta T cell
filtering for cell type memory B cell
filtering for cell type regulatory T cell
filtering for cell type CD8-positive, alpha-beta memory T cell
filtering for cell type gamma-delta T cell
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type mucosal invariant T cell
filtering for cell type CD16-negative, CD56-bright natural killer cell, human

  0%|          | 0/1 [00:08<?, ?it/s]

filtering for cell type activated CD8-positive, alpha-beta T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
All cell types are done

 82%|████████▏ | 527/642 [41:17<30:38, 15.99s/it]

Processing d7dcfd8f-2ee7-4385-b9ac-e074c23ed190 with size 935959767
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d7dcfd8f-2ee7-4385-b9ac-e074c23ed190.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 27197
filtering
filtering for cell type neuron
filtering for cell type fibroblast
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type macrophage
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type endothelial cell
filtering for cell type monocyte
filtering for cell type mesenchymal cell
filtering for cell type epithelial cell of proximal tubule
filtering for cell type neutrophil
filtering for cell type mast cell
filtering for cell type conventional dendritic cell
filtering for cell type lymphocyte
filtering for cell type mesenchymal stem cell
filtering for cell type myofibroblast cell
filtering for cell type plasmacytoid dendritic cell
filtering for cell type megakaryocyte
filtering for cell type kidney epithelial cell
filtering for cell type podocyte
filtering for cell type kidney cell
filtering for cell type erythroid lineage cell

  0%|          | 0/1 [00:14<?, ?it/s]

filtering for cell type kidney loop of Henle epithelial cell
All cell types are done

 82%|████████▏ | 528/642 [41:36<31:49, 16.75s/it]

Processing d87f3f91-dca4-494b-8993-c4e3008a8fa5 with size 6588243018
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d87f3f91-dca4-494b-8993-c4e3008a8fa5.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.45it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/d4f82ce26a144fcda943ada2959cba58-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/d4f82ce26a144fcda943ada2959cba58-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 15 RHS
At line 17 BOUNDS
At line 20 ENDATA
Problem MODEL has 1 rows, 2 columns and 2 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.03332 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type pvalb GABAergic cortical interneuron

  0%|          | 0/1 [00:23<?, ?it/s]

All cell types are done

 82%|████████▏ | 529/642 [42:02<36:37, 19.44s/it]

Processing d8da613f-e681-4c69-b463-e94f5e66847f with size 1337126539
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d8da613f-e681-4c69-b463-e94f5e66847f.parquet
Found 3 row groups
Indexing row groups for cell types and counts...

100%|██████████| 3/3 [00:02<00:00,  1.14it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/5bfb2765da6a45c28aafb2f97fdb6e55-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/5bfb2765da6a45c28aafb2f97fdb6e55-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 34 COLUMNS
At line 131 RHS
At line 161 BOUNDS
At line 165 ENDATA
Problem MODEL has 29 rows, 3 columns and 87 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 3 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 3 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                3.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 3 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type neuron
filtering for cell type fibroblast
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type macrophage
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type endothelial cell
filtering for cell type monocyte
filtering for cell type alveolar macrophage
filtering for cell type capillary endothelial cell
filtering for cell type pulmonary alveolar type 2 cell
filtering for cell type pericyte
filtering for cell type epithelial cell
filtering for cell type vein endothelial cell
filtering for cell type plasma cell
filtering for cell type regulatory T cell
filtering for cell type endothelial cell of artery
filtering for cell type respiratory basal cell
filtering for cell type mast cell
filtering for cell type dendritic cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type club cell
filtering for cell type alveolar adventitial fibroblast
filtering for cell type lung ciliated cell
filtering for cell type tracheobronchial smooth muscle cell
filtering for cell type mucus secreting cell

filtering for cell type lung goblet cell
filtering for cell type brush cell of tracheobronchial tree
reading row group 1
num rows 50000
filtering
filtering for cell type vein endothelial cell
filtering for cell type regulatory T cell
filtering for cell type endothelial cell of artery
filtering for cell type respiratory basal cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type club cell
filtering for cell type alveolar adventitial fibroblast
filtering for cell type lung ciliated cell
filtering for cell type tracheobronchial smooth muscle cell
filtering for cell type mucus secreting cell
filtering for cell type lung goblet cell
filtering for cell type brush cell of tracheobronchial tree

reading row group 2
num rows 16313
filtering
filtering for cell type respiratory basal cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type club cell
filtering for cell type alveolar adventitial fibroblast
filtering for cell type tracheobronchial smooth muscle cell

 67%|██████▋   | 2/3 [00:57<00:28, 28.74s/it]

filtering for cell type mucus secreting cell
filtering for cell type lung goblet cell
filtering for cell type brush cell of tracheobronchial tree
All cell types are done

 83%|████████▎ | 530/642 [43:07<1:01:44, 33.08s/it]

Processing d95ab381-2b7c-4885-b168-0097ed4e397f with size 40358091
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d95ab381-2b7c-4885-b168-0097ed4e397f.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 1378

  0%|          | 0/1 [00:01<?, ?it/s]

filtering
filtering for cell type retinal cone cell
All cell types are done

 83%|████████▎ | 531/642 [43:08<43:55, 23.74s/it]

Processing d967b47c-a9e6-4337-b2f4-977f690cb67f with size 1898170365
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/d967b47c-a9e6-4337-b2f4-977f690cb67f.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:00<00:00,  2.10it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/8b1855bcd3ca4cb19bd547dbe7ed7196-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/8b1855bcd3ca4cb19bd547dbe7ed7196-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 21 COLUMNS
At line 55 RHS
At line 72 BOUNDS
At line 75 ENDATA
Problem MODEL has 16 rows, 2 columns and 27 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 2 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 2 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type endothelial cell
filtering for cell type pericyte
filtering for cell type basal cell
filtering for cell type blood vessel endothelial cell
filtering for cell type mast cell
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type lymphocyte
filtering for cell type goblet cell
filtering for cell type melanocyte
filtering for cell type corneal epithelial cell
filtering for cell type ciliary muscle cell
filtering for cell type Schwann cell
filtering for cell type conjunctival epithelial cell

filtering for cell type corneal endothelial cell
reading row group 1
num rows 2309

 50%|█████     | 1/2 [00:25<00:25, 25.42s/it]

filtering
filtering for cell type mast cell
filtering for cell type corneal endothelial cell
All cell types are done

 83%|████████▎ | 532/642 [43:40<47:35, 25.96s/it]

Processing da684768-fb01-455b-9f0f-b63a3e2f844f with size 35174317
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/da684768-fb01-455b-9f0f-b63a3e2f844f.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 2303

  0%|          | 0/1 [00:01<?, ?it/s]

filtering
filtering for cell type skin fibroblast
All cell types are done

 83%|████████▎ | 533/642 [43:42<34:10, 18.81s/it]

Processing da75ce6d-a395-4abd-962b-267aadb99666 with size 457645993
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/da75ce6d-a395-4abd-962b-267aadb99666.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 16338
filtering
filtering for cell type stromal cell

  0%|          | 0/1 [00:06<?, ?it/s]

All cell types are done

 83%|████████▎ | 534/642 [43:50<28:05, 15.61s/it]

Processing db1d2c1b-2ee1-45d5-9d53-69a327cd77e6 with size 2143322735
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/db1d2c1b-2ee1-45d5-9d53-69a327cd77e6.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 31065
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:15<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 83%|████████▎ | 535/642 [44:06<28:07, 15.77s/it]

Processing db59611b-42de-4035-93aa-1ed39f38b467 with size 319017223
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/db59611b-42de-4035-93aa-1ed39f38b467.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 11574
filtering
filtering for cell type B cell
filtering for cell type erythrocyte
filtering for cell type plasma cell
filtering for cell type myeloid cell
filtering for cell type neutrophil
filtering for cell type mature NK T cell

  0%|          | 0/1 [00:05<?, ?it/s]

filtering for cell type dendritic cell
filtering for cell type platelet
All cell types are done

 83%|████████▎ | 536/642 [44:13<23:01, 13.04s/it]

Processing dbf0bd35-87f8-4b25-bc90-a3c54f379907 with size 53257200
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/dbf0bd35-87f8-4b25-bc90-a3c54f379907.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 3434
filtering
filtering for cell type B cell
filtering for cell type epithelial cell
filtering for cell type erythrocyte

  0%|          | 0/1 [00:01<?, ?it/s]

filtering for cell type myeloid cell
filtering for cell type neutrophil
filtering for cell type mature NK T cell
All cell types are done

 84%|████████▎ | 537/642 [44:15<17:25,  9.96s/it]

Processing dd018fc0-8da7-4033-a2ba-6b47de8ebb4f with size 1322042028
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/dd018fc0-8da7-4033-a2ba-6b47de8ebb4f.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 42127
filtering
filtering for cell type secretory cell
filtering for cell type basal cell of prostate epithelium
filtering for cell type luminal cell of prostate epithelium
filtering for cell type epithelial cell of urethra

  0%|          | 0/1 [00:19<?, ?it/s]

All cell types are done

 84%|████████▍ | 538/642 [44:37<23:10, 13.37s/it]

Processing dd03ce70-3243-4c96-9561-330cc461e4d7 with size 1043404792
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/dd03ce70-3243-4c96-9561-330cc461e4d7.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 23732
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:11<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 84%|████████▍ | 539/642 [44:49<22:28, 13.09s/it]

Processing ddb22b3d-a75c-4dd1-9730-dff7fc8ca530 with size 1797465822
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ddb22b3d-a75c-4dd1-9730-dff7fc8ca530.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.03it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/acc1f005fc724bd6bc5d7df9797a8bda-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/acc1f005fc724bd6bc5d7df9797a8bda-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 17 COLUMNS
At line 48 RHS
At line 61 BOUNDS
At line 64 ENDATA
Problem MODEL has 12 rows, 2 columns and 24 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 2 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 2 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type blood vessel endothelial cell
filtering for cell type periportal region hepatocyte
filtering for cell type centrilobular region hepatocyte
filtering for cell type Kupffer cell
filtering for cell type midzonal region hepatocyte
filtering for cell type endothelial cell of pericentral hepatic sinusoid
filtering for cell type inflammatory macrophage
filtering for cell type hepatic stellate cell

filtering for cell type cholangiocyte
filtering for cell type erythroid lineage cell
reading row group 1
num rows 23295
filtering
filtering for cell type inflammatory macrophage
filtering for cell type hepatic stellate cell

 50%|█████     | 1/2 [00:36<00:36, 36.26s/it]

filtering for cell type cholangiocyte
filtering for cell type erythroid lineage cell
All cell types are done

 84%|████████▍ | 540/642 [45:32<37:40, 22.16s/it]

Processing de104f7e-14fa-4795-bd19-b5ee2c1563e0 with size 4824835588
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/de104f7e-14fa-4795-bd19-b5ee2c1563e0.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 45252
filtering
filtering for cell type L2/3-6 intratelencephalic projecting glutamatergic neuron

  0%|          | 0/1 [00:20<?, ?it/s]

All cell types are done

 84%|████████▍ | 541/642 [45:53<36:43, 21.82s/it]

Processing de17ac25-550a-4018-be75-bbb485a0636e with size 11657349
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/de17ac25-550a-4018-be75-bbb485a0636e.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 395

  0%|          | 0/1 [00:00<?, ?it/s]

filtering
filtering for cell type myeloid cell
All cell types are done

 84%|████████▍ | 542/642 [45:55<26:01, 15.62s/it]

Processing de2c780c-1747-40bd-9ccf-9588ec186cee with size 1497992144
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/de2c780c-1747-40bd-9ccf-9588ec186cee.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.23it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/6d72c8b2d1e0410e9f76484ca28c0a51-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/6d72c8b2d1e0410e9f76484ca28c0a51-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 19 COLUMNS
At line 54 RHS
At line 69 BOUNDS
At line 72 ENDATA
Problem MODEL has 14 rows, 2 columns and 28 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 2 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 2 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type classical monocyte
filtering for cell type natural killer cell
filtering for cell type erythrocyte
filtering for cell type non-classical monocyte
filtering for cell type CD4-positive helper T cell
filtering for cell type dendritic cell
filtering for cell type effector CD8-positive, alpha-beta T cell
filtering for cell type platelet
filtering for cell type blood cell
filtering for cell type effector CD4-positive, alpha-beta T cell
filtering for cell type intermediate monocyte
filtering for cell type IgG-negative class switched memory B cell

filtering for cell type IgG memory B cell
reading row group 1
num rows 9572
filtering
filtering for cell type blood cell
filtering for cell type effector CD4-positive, alpha-beta T cell
filtering for cell type intermediate monocyte
filtering for cell type IgG-negative class switched memory B cell
filtering for cell type IgG memory B cell

 50%|█████     | 1/2 [00:28<00:28, 28.37s/it]

All cell types are done

 85%|████████▍ | 543/642 [46:29<35:06, 21.28s/it]

Processing de94c504-4b58-4f42-b68d-74a8e4892f0e with size 356479487
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/de94c504-4b58-4f42-b68d-74a8e4892f0e.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 15243
filtering
filtering for cell type endothelial cell
filtering for cell type pericyte
filtering for cell type skin fibroblast
filtering for cell type keratinocyte

  0%|          | 0/1 [00:06<?, ?it/s]

filtering for cell type leukocyte
filtering for cell type melanocyte
All cell types are done

 85%|████████▍ | 544/642 [46:38<28:29, 17.45s/it]

Processing de985818-285f-4f59-9dbd-d74968fddba3 with size 903416606
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/de985818-285f-4f59-9dbd-d74968fddba3.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 31696
filtering
filtering for cell type B cell
filtering for cell type luminal adaptive secretory precursor cell of mammary gland
filtering for cell type luminal hormone-sensing cell of mammary gland
filtering for cell type basal-myoepithelial cell of mammary gland

  0%|          | 0/1 [00:13<?, ?it/s]

filtering for cell type endothelial cell of lymphatic vessel
All cell types are done

 85%|████████▍ | 545/642 [46:55<28:05, 17.38s/it]

Processing df287f8d-f50d-4620-ab96-489d559e6adc with size 26217802
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/df287f8d-f50d-4620-ab96-489d559e6adc.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 1295

  0%|          | 0/1 [00:00<?, ?it/s]

filtering
filtering for cell type smooth muscle cell of prostate
filtering for cell type fibroblast of connective tissue of prostate
All cell types are done

 85%|████████▌ | 546/642 [46:56<20:10, 12.61s/it]

Processing dfdf1ae2-d624-4004-9353-f18b902f6bca with size 745799808
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/dfdf1ae2-d624-4004-9353-f18b902f6bca.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 40821
filtering
filtering for cell type macrophage
filtering for cell type monocyte
filtering for cell type non-classical monocyte
filtering for cell type conventional dendritic cell
filtering for cell type plasmacytoid dendritic cell
filtering for cell type Kupffer cell
filtering for cell type myeloid leukocyte

  0%|          | 0/1 [00:19<?, ?it/s]

All cell types are done

 85%|████████▌ | 547/642 [47:17<24:00, 15.16s/it]

Processing e006d4e3-35fa-44b4-9981-09a66c4322e5 with size 120368177
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e006d4e3-35fa-44b4-9981-09a66c4322e5.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 4211
filtering
filtering for cell type enteric smooth muscle cell
filtering for cell type interstitial cell of Cajal

  0%|          | 0/1 [00:02<?, ?it/s]

filtering for cell type smooth muscle cell of large intestine
All cell types are done

 85%|████████▌ | 548/642 [47:22<18:40, 11.92s/it]

Processing e067e5ca-e53e-485f-aa8e-efd5435229c8 with size 1119843088
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e067e5ca-e53e-485f-aa8e-efd5435229c8.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 39176
filtering
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type epithelial cell of proximal tubule
filtering for cell type kidney loop of Henle thick ascending limb epithelial cell
filtering for cell type kidney distal convoluted tubule epithelial cell
filtering for cell type leukocyte
filtering for cell type kidney loop of Henle thin ascending limb epithelial cell
filtering for cell type podocyte
filtering for cell type parietal epithelial cell
filtering for cell type renal alpha-intercalated cell
filtering for cell type renal principal cell
filtering for cell type renal beta-intercalated cell
filtering for cell type mesangial cell
All cell types are done

  0%|          | 0/1 [00:25<?, ?it/s]
 86%|████████▌ | 549/642 [47:52<26:59, 17.42s/it]

Processing e1cc3162-6032-4e88-ad6b-57e8a65e0c55 with size 992547918
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e1cc3162-6032-4e88-ad6b-57e8a65e0c55.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 74626
filtering
filtering for cell type type I muscle cell
filtering for cell type type II muscle cell
filtering for cell type muscle cell

  0%|          | 0/1 [00:48<?, ?it/s]

All cell types are done

 86%|████████▌ | 550/642 [48:45<43:05, 28.10s/it]

Processing e1f595f6-ba2c-495e-9bee-7056f116b1e4 with size 7606666239
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e1f595f6-ba2c-495e-9bee-7056f116b1e4.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 107301
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [01:08<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 86%|████████▌ | 551/642 [49:55<1:01:45, 40.72s/it]

Processing e22c2ab4-c025-4804-b7a3-0b0ebd48c87a with size 78613970
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e22c2ab4-c025-4804-b7a3-0b0ebd48c87a.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 5156
filtering
filtering for cell type smooth muscle cell
filtering for cell type blood vessel smooth muscle cell
filtering for cell type lung pericyte
filtering for cell type smooth muscle cell of the pulmonary artery

  0%|          | 0/1 [00:03<?, ?it/s]

All cell types are done

 86%|████████▌ | 552/642 [50:00<45:01, 30.02s/it]

Processing e2a325e2-5633-4950-ae46-ebff70979e3b with size 280113458
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e2a325e2-5633-4950-ae46-ebff70979e3b.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 4683

  0%|          | 0/1 [00:02<?, ?it/s]

filtering
filtering for cell type lamp5 GABAergic cortical interneuron
All cell types are done

 86%|████████▌ | 553/642 [50:04<32:45, 22.08s/it]

Processing e2a3c32d-71e2-4f38-b19c-dfcb8729cf46 with size 478208450
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e2a3c32d-71e2-4f38-b19c-dfcb8729cf46.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 24544
filtering
filtering for cell type secretory cell
filtering for cell type basal cell of prostate epithelium
filtering for cell type luminal cell of prostate epithelium
filtering for cell type epithelial cell of urethra

  0%|          | 0/1 [00:14<?, ?it/s]

filtering for cell type neuroendocrine cell
All cell types are done

 86%|████████▋ | 554/642 [50:20<29:50, 20.35s/it]

Processing e347396c-a7ff-4691-9f7a-99a43555ca18 with size 18264013
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e347396c-a7ff-4691-9f7a-99a43555ca18.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 1417
filtering
filtering for cell type vein endothelial cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type hepatic stellate cell

  0%|          | 0/1 [00:01<?, ?it/s]

All cell types are done

 86%|████████▋ | 555/642 [50:22<21:29, 14.82s/it]

Processing e34f3f89-3a48-4173-a06a-9e9803f2e2b9 with size 1417453404
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e34f3f89-3a48-4173-a06a-9e9803f2e2b9.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 57855
filtering
filtering for cell type oligodendrocyte

  0%|          | 0/1 [00:32<?, ?it/s]

All cell types are done

 87%|████████▋ | 556/642 [50:56<29:16, 20.42s/it]

Processing e3a7e927-2632-4575-993d-d0905cd5da8b with size 4313554100
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e3a7e927-2632-4575-993d-d0905cd5da8b.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 221315
filtering
filtering for cell type T cell

  0%|          | 0/1 [02:04<?, ?it/s]

All cell types are done

 87%|████████▋ | 557/642 [53:01<1:13:23, 51.81s/it]

Processing e4710a02-8abc-48d5-a3e8-9ae7e9d79bdb with size 14720932635
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e4710a02-8abc-48d5-a3e8-9ae7e9d79bdb.parquet
Found 5 row groups
Indexing row groups for cell types and counts...

100%|██████████| 5/5 [00:05<00:00,  1.08s/it]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/8ba3660c66d944ceba445bac1ef00345-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/8ba3660c66d944ceba445bac1ef00345-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 27 RHS
At line 29 BOUNDS
At line 35 ENDATA
Problem MODEL has 1 rows, 5 columns and 5 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.00132 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 4
num rows 22434
filtering
filtering for cell type neuron

  0%|          | 0/1 [00:09<?, ?it/s]

All cell types are done

 87%|████████▋ | 558/642 [53:16<57:13, 40.88s/it]

Processing e47c65a8-7d2f-48b8-908e-04ea6505fa26 with size 2183849256
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e47c65a8-7d2f-48b8-908e-04ea6505fa26.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.78it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/d9847c2b97db4185a5a56761f00fc108-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/d9847c2b97db4185a5a56761f00fc108-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 8 COLUMNS
At line 21 RHS
At line 25 BOUNDS
At line 28 ENDATA
Problem MODEL has 3 rows, 2 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.0672818 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type capillary endothelial cell
filtering for cell type vein endothelial cell

  0%|          | 0/1 [00:23<?, ?it/s]

filtering for cell type endothelial cell of artery
All cell types are done

 87%|████████▋ | 559/642 [53:42<50:19, 36.37s/it]

Processing e4ddac12-f48f-4455-8e8d-c2a48a683437 with size 7836748044
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e4ddac12-f48f-4455-8e8d-c2a48a683437.parquet
Found 3 row groups
Indexing row groups for cell types and counts...

100%|██████████| 3/3 [00:02<00:00,  1.17it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/29389f7a65e94c7ca7591ee3b9d76eb1-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/29389f7a65e94c7ca7591ee3b9d76eb1-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 9 COLUMNS
At line 31 RHS
At line 36 BOUNDS
At line 40 ENDATA
Problem MODEL has 4 rows, 3 columns and 12 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.825429 - 0.00 seconds
Cgl0003I 0 fixed, 1 tightened bounds, 0 strengthened rows, 0 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type VIP GABAergic cortical interneuron
filtering for cell type lamp5 GABAergic cortical interneuron
filtering for cell type sncg GABAergic cortical interneuron

  0%|          | 0/1 [00:22<?, ?it/s]

filtering for cell type caudal ganglionic eminence derived interneuron
All cell types are done

 87%|████████▋ | 560/642 [54:08<45:41, 33.44s/it]

Processing e500acbf-f166-4c46-b290-f93506cf26d3 with size 1139928919
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e500acbf-f166-4c46-b290-f93506cf26d3.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 37428
filtering
filtering for cell type malignant cell

  0%|          | 0/1 [00:17<?, ?it/s]

filtering for cell type mesothelial cell
All cell types are done

 87%|████████▋ | 561/642 [54:27<39:03, 28.94s/it]

Processing e5233a94-9e43-418c-8209-6f1400c31530 with size 3552713715
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e5233a94-9e43-418c-8209-6f1400c31530.parquet
Found 3 row groups
Indexing row groups for cell types and counts...

100%|██████████| 3/3 [00:02<00:00,  1.11it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/c135b4957e644fd8b53b9403545d856f-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/c135b4957e644fd8b53b9403545d856f-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 35 COLUMNS
At line 134 RHS
At line 165 BOUNDS
At line 169 ENDATA
Problem MODEL has 30 rows, 3 columns and 89 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 3 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 3 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                3.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 3 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type natural killer cell
filtering for cell type monocyte
filtering for cell type capillary endothelial cell
filtering for cell type vein endothelial cell
filtering for cell type erythrocyte
filtering for cell type memory B cell
filtering for cell type enterocyte
filtering for cell type endothelial cell of artery
filtering for cell type gamma-delta T cell
filtering for cell type CD4-positive helper T cell
filtering for cell type mast cell
filtering for cell type dendritic cell
filtering for cell type stem cell
filtering for cell type foveolar cell of stomach
filtering for cell type IgA plasma cell
filtering for cell type epithelial cell of esophagus
filtering for cell type activated CD8-positive, alpha-beta T cell
filtering for cell type memory T cell
filtering for cell type mucous neck cell
filtering for cell type intestine goblet cell
filtering for cell type IgG plasma cell
filtering for cell type enteroendocrine cell
filtering for cell type natural T-regulatory cell
filtering for cell type peptic cell
filtering for cell type type G enteroendocrine cell
filtering for cell type P/D1 enteroendocrine cell
filtering for cell type glandular cell of esophagus
filtering for cell type parietal cell

reading row group 1
num rows 50000
filtering
filtering for cell type capillary endothelial cell
filtering for cell type erythrocyte
filtering for cell type memory B cell
filtering for cell type endothelial cell of artery
filtering for cell type CD4-positive helper T cell
filtering for cell type mast cell
filtering for cell type dendritic cell
filtering for cell type stem cell
filtering for cell type IgA plasma cell
filtering for cell type activated CD8-positive, alpha-beta T cell
filtering for cell type memory T cell
filtering for cell type mucous neck cell
filtering for cell type intestine goblet cell
filtering for cell type IgG plasma cell
filtering for cell type enteroendocrine cell
filtering for cell type natural T-regulatory cell
filtering for cell type peptic cell
filtering for cell type type G enteroendocrine cell
filtering for cell type P/D1 enteroendocrine cell
filtering for cell type glandular cell of esophagus
filtering for cell type parietal cell

reading row group 2
num rows 46583
filtering
filtering for cell type CD4-positive helper T cell
filtering for cell type memory T cell
filtering for cell type intestine goblet cell
filtering for cell type IgG plasma cell
filtering for cell type natural T-regulatory cell
filtering for cell type peptic cell

 67%|██████▋   | 2/3 [01:07<00:33, 33.50s/it]

filtering for cell type type G enteroendocrine cell
filtering for cell type P/D1 enteroendocrine cell
filtering for cell type parietal cell
All cell types are done

 88%|████████▊ | 562/642 [55:48<59:28, 44.60s/it]

Processing e59a4394-80db-42e4-85e6-8f0e59b81f42 with size 10941314321
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e59a4394-80db-42e4-85e6-8f0e59b81f42.parquet
Found 6 row groups
Indexing row groups for cell types and counts...

100%|██████████| 6/6 [00:05<00:00,  1.04it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/4b3ff7acee5549269e98e2a0089de845-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/4b3ff7acee5549269e98e2a0089de845-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 31 RHS
At line 33 BOUNDS
At line 40 ENDATA
Problem MODEL has 1 rows, 6 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.04 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 5
num rows 35699
filtering
filtering for cell type neuroblast (sensu Vertebrata)

  0%|          | 0/1 [00:14<?, ?it/s]

All cell types are done

 88%|████████▊ | 563/642 [56:09<49:31, 37.61s/it]

Processing e5b1115b-a486-49bb-bda3-8261822836e0 with size 2088591062
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e5b1115b-a486-49bb-bda3-8261822836e0.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 35359
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:16<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 88%|████████▊ | 564/642 [56:26<40:50, 31.41s/it]

Processing e5f5d954-cf0e-4bd8-9346-8d1ddf15a08b with size 45886043
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e5f5d954-cf0e-4bd8-9346-8d1ddf15a08b.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 2487
filtering
filtering for cell type B cell
filtering for cell type epithelial cell
filtering for cell type erythrocyte
filtering for cell type myeloid cell
filtering for cell type neutrophil
filtering for cell type mast cell
filtering for cell type mature NK T cell

  0%|          | 0/1 [00:01<?, ?it/s]

filtering for cell type ionocyte
All cell types are done

 88%|████████▊ | 565/642 [56:28<29:02, 22.62s/it]

Processing e6361237-ac4e-4c5d-ad8f-f16aca0c0a8f with size 3290302977
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e6361237-ac4e-4c5d-ad8f-f16aca0c0a8f.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.52it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/8bdd1a9fe6234892bef12976fcd419e5-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/8bdd1a9fe6234892bef12976fcd419e5-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 11 COLUMNS
At line 30 RHS
At line 37 BOUNDS
At line 40 ENDATA
Problem MODEL has 6 rows, 2 columns and 12 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.378378 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               1
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell

  0%|          | 0/1 [00:22<?, ?it/s]

filtering for cell type microglial cell
All cell types are done

 88%|████████▊ | 566/642 [56:53<29:30, 23.29s/it]

Processing e6b2ce27-681b-4409-a053-2681875936e5 with size 2822386926
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e6b2ce27-681b-4409-a053-2681875936e5.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 40144
filtering
filtering for cell type neuron

  0%|          | 0/1 [00:16<?, ?it/s]

All cell types are done

 88%|████████▊ | 567/642 [57:11<26:55, 21.54s/it]

Processing e6dad530-418b-47f9-af6e-472e56a7b314 with size 2504806272
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e6dad530-418b-47f9-af6e-472e56a7b314.parquet
Found 3 row groups
Indexing row groups for cell types and counts...

100%|██████████| 3/3 [00:01<00:00,  2.96it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/f68f6290b22d46be8ff4968acf4456bc-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/f68f6290b22d46be8ff4968acf4456bc-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 15 COLUMNS
At line 49 RHS
At line 60 BOUNDS
At line 64 ENDATA
Problem MODEL has 10 rows, 3 columns and 24 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 3 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 3 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                3.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 3 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type astrocyte
filtering for cell type retinal rod cell
filtering for cell type myeloid cell
filtering for cell type retinal ganglion cell
filtering for cell type amacrine cell
filtering for cell type retinal bipolar neuron
filtering for cell type Mueller cell
filtering for cell type retinal cone cell
filtering for cell type retina horizontal cell
filtering for cell type retinal pigment epithelial cell

reading row group 1
num rows 50000
filtering
filtering for cell type retinal ganglion cell
filtering for cell type retinal cone cell
filtering for cell type retina horizontal cell

filtering for cell type retinal pigment epithelial cell
reading row group 2
num rows 55

 67%|██████▋   | 2/3 [00:42<00:21, 21.26s/it]

filtering
filtering for cell type retinal pigment epithelial cell
All cell types are done

 88%|████████▊ | 568/642 [57:58<36:03, 29.24s/it]

Processing e8681d74-ac9e-4be5-be14-1cf1bbd54dd7 with size 2280042298
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e8681d74-ac9e-4be5-be14-1cf1bbd54dd7.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 31307
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:13<?, ?it/s]

filtering for cell type leukocyte
filtering for cell type choroid plexus epithelial cell
filtering for cell type ependymal cell
All cell types are done

 89%|████████▊ | 569/642 [58:13<30:15, 24.87s/it]

Processing e871881f-b42d-4500-906d-0972a14ba47d with size 408646873
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e871881f-b42d-4500-906d-0972a14ba47d.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 20515
filtering
filtering for cell type fibroblast
filtering for cell type mesothelial cell
filtering for cell type myofibroblast cell
filtering for cell type fibroblast of lung
filtering for cell type adventitial cell
filtering for cell type bronchus fibroblast of lung
filtering for cell type myelinating Schwann cell
filtering for cell type non-myelinating Schwann cell

  0%|          | 0/1 [00:10<?, ?it/s]

filtering for cell type lung perichondrial fibroblast
All cell types are done

 89%|████████▉ | 570/642 [58:27<25:54, 21.60s/it]

Processing e8a11a27-9c47-4673-b65d-11b9cd6065e1 with size 472278298
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e8a11a27-9c47-4673-b65d-11b9cd6065e1.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 9096
filtering
filtering for cell type pulmonary alveolar type 2 cell
filtering for cell type basal cell
filtering for cell type pulmonary alveolar type 1 cell
filtering for cell type club cell
filtering for cell type epithelial cell of lung
filtering for cell type lung secretory cell
filtering for cell type glandular epithelial cell
filtering for cell type neuroendocrine cell
filtering for cell type respiratory epithelial cell

  0%|          | 0/1 [00:05<?, ?it/s]

filtering for cell type squamous epithelial cell
filtering for cell type lung neuroendocrine cell
All cell types are done

 89%|████████▉ | 571/642 [58:34<20:22, 17.21s/it]

Processing e8ac3386-31d4-48ba-aa70-1bae0cf020e7 with size 1538671000
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e8ac3386-31d4-48ba-aa70-1bae0cf020e7.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 21443
filtering
filtering for cell type lamp5 GABAergic cortical interneuron

  0%|          | 0/1 [00:09<?, ?it/s]

All cell types are done

 89%|████████▉ | 572/642 [58:43<17:31, 15.03s/it]

Processing e9175006-8978-4417-939f-819855eab80e with size 367023727
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/e9175006-8978-4417-939f-819855eab80e.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 14072
filtering
filtering for cell type classical monocyte
filtering for cell type neutrophil
filtering for cell type conventional dendritic cell
filtering for cell type plasmacytoid dendritic cell

  0%|          | 0/1 [00:06<?, ?it/s]

All cell types are done

 89%|████████▉ | 573/642 [58:51<14:34, 12.67s/it]

Processing ea01c125-67a7-4bd3-a8b0-e1b53a011b7e with size 169542515
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ea01c125-67a7-4bd3-a8b0-e1b53a011b7e.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 4636
filtering
filtering for cell type mesenchymal stem cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:01<?, ?it/s]

filtering for cell type epithelial cell of nephron
All cell types are done

 89%|████████▉ | 574/642 [58:54<11:13,  9.91s/it]

Processing ea251de5-c764-4f7c-add0-8141b1061faf with size 1214746930
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ea251de5-c764-4f7c-add0-8141b1061faf.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 19161
filtering
filtering for cell type fibroblast

  0%|          | 0/1 [00:08<?, ?it/s]

All cell types are done

 90%|████████▉ | 575/642 [59:03<10:43,  9.60s/it]

Processing ea426edb-4e86-4c53-ab17-5b952d94a31e with size 31974982
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ea426edb-4e86-4c53-ab17-5b952d94a31e.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 2113
filtering
filtering for cell type smooth muscle cell of prostate
filtering for cell type fibroblast of connective tissue of prostate

  0%|          | 0/1 [00:01<?, ?it/s]

All cell types are done

 90%|████████▉ | 576/642 [59:05<08:08,  7.39s/it]

Processing ea786a06-5855-48b7-80d7-0313a21a2044 with size 64973376
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ea786a06-5855-48b7-80d7-0313a21a2044.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 4792
filtering
filtering for cell type B cell
filtering for cell type plasma cell
filtering for cell type myeloid cell
filtering for cell type neutrophil
filtering for cell type mature NK T cell
filtering for cell type dendritic cell
filtering for cell type platelet

  0%|          | 0/1 [00:02<?, ?it/s]

All cell types are done

 90%|████████▉ | 577/642 [59:09<06:49,  6.30s/it]

Processing ea7b95cf-1967-4431-9ee8-ec85ff793360 with size 333669960
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ea7b95cf-1967-4431-9ee8-ec85ff793360.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 8102

  0%|          | 0/1 [00:03<?, ?it/s]

filtering
filtering for cell type macrophage
All cell types are done

 90%|█████████ | 578/642 [59:13<05:57,  5.58s/it]

Processing ea95cdd5-cf7e-4d5d-a0bd-032776d32ae5 with size 679150344
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ea95cdd5-cf7e-4d5d-a0bd-032776d32ae5.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 16319
filtering
filtering for cell type astrocyte of the cerebral cortex

  0%|          | 0/1 [00:07<?, ?it/s]

All cell types are done

 90%|█████████ | 579/642 [59:21<06:37,  6.31s/it]

Processing ebaaa22f-fbaa-4a9c-aa62-b938a4e2d319 with size 604470031
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ebaaa22f-fbaa-4a9c-aa62-b938a4e2d319.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 9957
filtering
filtering for cell type placental villous trophoblast
filtering for cell type extravillous trophoblast

  0%|          | 0/1 [00:04<?, ?it/s]

All cell types are done

 90%|█████████ | 580/642 [59:27<06:29,  6.29s/it]

Processing ebc2e1ff-c8f9-466a-acf4-9d291afaf8b3 with size 14626761772
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ebc2e1ff-c8f9-466a-acf4-9d291afaf8b3.parquet
Found 17 row groups
Indexing row groups for cell types and counts...

100%|██████████| 17/17 [00:20<00:00,  1.18s/it]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/cb419d7d614843bcb645c3593049f312-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/cb419d7d614843bcb645c3593049f312-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 21 COLUMNS
At line 344 RHS
At line 361 BOUNDS
At line 379 ENDATA
Problem MODEL has 16 rows, 17 columns and 271 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 17 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 17 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                17.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 17 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type classical monocyte
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type double-positive, alpha-beta thymocyte
filtering for cell type non-classical monocyte
filtering for cell type gamma-delta T cell
filtering for cell type mast cell
filtering for cell type dendritic cell
filtering for cell type mucosal invariant T cell
filtering for cell type plasmablast
filtering for cell type hematopoietic stem cell
filtering for cell type blood cell

filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type double negative T regulatory cell
reading row group 1
num rows 50000
filtering
filtering for cell type double-positive, alpha-beta thymocyte
filtering for cell type mast cell
filtering for cell type mucosal invariant T cell
filtering for cell type plasmablast
filtering for cell type hematopoietic stem cell
filtering for cell type blood cell

filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type double negative T regulatory cell
reading row group 2
num rows 50000
filtering
filtering for cell type double-positive, alpha-beta thymocyte
filtering for cell type mast cell
filtering for cell type mucosal invariant T cell
filtering for cell type hematopoietic stem cell
filtering for cell type blood cell

filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type double negative T regulatory cell
reading row group 3
num rows 50000
filtering
filtering for cell type mast cell
filtering for cell type hematopoietic stem cell
filtering for cell type megakaryocyte-erythroid progenitor cell

filtering for cell type double negative T regulatory cell
reading row group 4
num rows 50000
filtering
filtering for cell type mast cell
filtering for cell type hematopoietic stem cell
filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type double negative T regulatory cell

reading row group 5
num rows 50000
filtering
filtering for cell type mast cell
filtering for cell type hematopoietic stem cell
filtering for cell type megakaryocyte-erythroid progenitor cell

filtering for cell type double negative T regulatory cell
reading row group 6
num rows 50000
filtering
filtering for cell type mast cell
filtering for cell type hematopoietic stem cell
filtering for cell type megakaryocyte-erythroid progenitor cell

filtering for cell type double negative T regulatory cell
reading row group 7
num rows 50000
filtering
filtering for cell type mast cell
filtering for cell type hematopoietic stem cell
filtering for cell type megakaryocyte-erythroid progenitor cell

filtering for cell type double negative T regulatory cell
reading row group 8
num rows 50000
filtering
filtering for cell type mast cell
filtering for cell type hematopoietic stem cell

filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type double negative T regulatory cell
reading row group 9
num rows 50000
filtering
filtering for cell type mast cell

filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type double negative T regulatory cell
reading row group 10
num rows 50000
filtering
filtering for cell type mast cell
filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type double negative T regulatory cell

reading row group 11
num rows 50000
filtering

filtering for cell type mast cell
filtering for cell type double negative T regulatory cell
reading row group 12
num rows 50000
filtering
filtering for cell type mast cell

filtering for cell type double negative T regulatory cell
reading row group 13
num rows 50000
filtering
filtering for cell type mast cell

filtering for cell type double negative T regulatory cell
reading row group 14
num rows 50000
filtering
filtering for cell type mast cell

filtering for cell type double negative T regulatory cell
reading row group 15
num rows 50000
filtering
filtering for cell type mast cell

filtering for cell type double negative T regulatory cell
reading row group 16
num rows 36148
filtering

 94%|█████████▍| 16/17 [06:22<00:23, 23.92s/it]

filtering for cell type mast cell
filtering for cell type double negative T regulatory cell
All cell types are done

 90%|█████████ | 581/642 [1:06:16<2:09:08, 127.03s/it]

Processing ec6ceff8-c8bc-488d-b6bf-30df2fa92169 with size 2395724434
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ec6ceff8-c8bc-488d-b6bf-30df2fa92169.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.68it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/4102987cf2f94b0db4e07ca158840717-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/4102987cf2f94b0db4e07ca158840717-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 16 COLUMNS
At line 45 RHS
At line 57 BOUNDS
At line 60 ENDATA
Problem MODEL has 11 rows, 2 columns and 22 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 2 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 2 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type neuron
filtering for cell type B cell
filtering for cell type endothelial cell
filtering for cell type erythrocyte
filtering for cell type mature NK T cell
filtering for cell type lymphocyte
filtering for cell type hepatocyte
filtering for cell type neoplastic cell
filtering for cell type Kupffer cell
filtering for cell type hepatic stellate cell

filtering for cell type cholangiocyte
reading row group 1
num rows 17110
filtering
filtering for cell type neuron
filtering for cell type B cell
filtering for cell type erythrocyte
filtering for cell type lymphocyte
filtering for cell type Kupffer cell

 50%|█████     | 1/2 [00:30<00:30, 30.41s/it]

filtering for cell type hepatic stellate cell
filtering for cell type cholangiocyte
All cell types are done

 91%|█████████ | 582/642 [1:06:52<1:39:36, 99.61s/it]

Processing ecd9230d-c571-4dab-abd3-8b54c74833f0 with size 2704875631
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ecd9230d-c571-4dab-abd3-8b54c74833f0.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 46453
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:20<?, ?it/s]

filtering for cell type Bergmann glial cell
filtering for cell type choroid plexus epithelial cell
filtering for cell type ependymal cell
All cell types are done

 91%|█████████ | 583/642 [1:07:13<1:14:47, 76.06s/it]

Processing ecf2e08e-2032-4a9e-b466-b65b395f4a02 with size 2895575454
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ecf2e08e-2032-4a9e-b466-b65b395f4a02.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.74it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/2cbe695c8a4d45adb4f9418d57f38bc6-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/2cbe695c8a4d45adb4f9418d57f38bc6-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 8 COLUMNS
At line 21 RHS
At line 25 BOUNDS
At line 28 ENDATA
Problem MODEL has 3 rows, 2 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.220604 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type placental villous trophoblast
filtering for cell type extravillous trophoblast
filtering for cell type syncytiotrophoblast cell

  0%|          | 0/1 [00:21<?, ?it/s]

All cell types are done

 91%|█████████ | 584/642 [1:07:37<58:38, 60.67s/it]

Processing ed11cc3e-2947-407c-883c-c53b043917c3 with size 570964293
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ed11cc3e-2947-407c-883c-c53b043917c3.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 8573
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:04<?, ?it/s]

filtering for cell type ependymal cell
All cell types are done

 91%|█████████ | 585/642 [1:07:42<41:44, 43.94s/it]

Processing ed2b673b-0279-454a-998c-3eec361edf54 with size 2609298703
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ed2b673b-0279-454a-998c-3eec361edf54.parquet
Found 3 row groups
Indexing row groups for cell types and counts...

100%|██████████| 3/3 [00:02<00:00,  1.34it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/e3c174ffc93d4f6699dfff3fe2855e50-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/e3c174ffc93d4f6699dfff3fe2855e50-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 19 RHS
At line 21 BOUNDS
At line 25 ENDATA
Problem MODEL has 1 rows, 3 columns and 3 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.0388 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 2
num rows 42816
filtering
filtering for cell type fibroblast of cardiac tissue

  0%|          | 0/1 [00:17<?, ?it/s]

All cell types are done

 91%|█████████▏| 586/642 [1:08:03<34:32, 37.02s/it]

Processing ed33c203-233a-476a-a56b-28da945fdd32 with size 2232413312
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ed33c203-233a-476a-a56b-28da945fdd32.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 32638
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:14<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 91%|█████████▏| 587/642 [1:08:19<28:03, 30.62s/it]

Processing ed419b4e-db9b-40f1-8593-68fdf8dfb076 with size 671058035
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ed419b4e-db9b-40f1-8593-68fdf8dfb076.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 18011
filtering
filtering for cell type astrocyte
filtering for cell type microglial cell
filtering for cell type Mueller cell
filtering for cell type retinal pigment epithelial cell

  0%|          | 0/1 [00:08<?, ?it/s]

All cell types are done

 92%|█████████▏| 588/642 [1:08:28<21:42, 24.13s/it]

Processing ed5d841d-6346-47d4-ab2f-7119ad7e3a35 with size 4853086268
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ed5d841d-6346-47d4-ab2f-7119ad7e3a35.parquet
Found 4 row groups
Indexing row groups for cell types and counts...

100%|██████████| 4/4 [00:04<00:00,  1.09s/it]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/f3c7363abd6140d38b01d06584c80ec3-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/f3c7363abd6140d38b01d06584c80ec3-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 34 COLUMNS
At line 163 RHS
At line 193 BOUNDS
At line 198 ENDATA
Problem MODEL has 29 rows, 4 columns and 116 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 4 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 4 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                4.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 4 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type naive thymus-derived CD4-positive, alpha-beta T cell
filtering for cell type central memory CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive monocyte
filtering for cell type effector memory CD8-positive, alpha-beta T cell
filtering for cell type naive B cell
filtering for cell type erythrocyte
filtering for cell type naive thymus-derived CD8-positive, alpha-beta T cell
filtering for cell type memory B cell
filtering for cell type double negative thymocyte
filtering for cell type gamma-delta T cell
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type conventional dendritic cell
filtering for cell type mucosal invariant T cell
filtering for cell type CD14-low, CD16-positive monocyte
filtering for cell type CD16-negative, CD56-bright natural killer cell, human
filtering for cell type plasmacytoid dendritic cell
filtering for cell type platelet
filtering for cell type plasmablast
filtering for cell type central memory CD8-positive, alpha-beta T cell
filtering for cell type hematopoietic stem cell
filtering for cell type innate lymphoid cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type naive regulatory T cell

filtering for cell type myeloid dendritic cell, human
filtering for cell type memory regulatory T cell
reading row group 1
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type erythrocyte
filtering for cell type double negative thymocyte
filtering for cell type effector memory CD4-positive, alpha-beta T cell
filtering for cell type CD16-negative, CD56-bright natural killer cell, human
filtering for cell type plasmacytoid dendritic cell
filtering for cell type platelet
filtering for cell type plasmablast
filtering for cell type central memory CD8-positive, alpha-beta T cell
filtering for cell type hematopoietic stem cell
filtering for cell type innate lymphoid cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type naive regulatory T cell
filtering for cell type myeloid dendritic cell, human

filtering for cell type memory regulatory T cell
reading row group 2
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type erythrocyte
filtering for cell type double negative thymocyte
filtering for cell type CD16-negative, CD56-bright natural killer cell, human
filtering for cell type plasmablast
filtering for cell type central memory CD8-positive, alpha-beta T cell
filtering for cell type hematopoietic stem cell
filtering for cell type innate lymphoid cell
filtering for cell type naive regulatory T cell
filtering for cell type myeloid dendritic cell, human
filtering for cell type memory regulatory T cell

reading row group 3
num rows 11764
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type erythrocyte
filtering for cell type double negative thymocyte
filtering for cell type plasmablast
filtering for cell type central memory CD8-positive, alpha-beta T cell
filtering for cell type hematopoietic stem cell
filtering for cell type innate lymphoid cell
filtering for cell type naive regulatory T cell
filtering for cell type myeloid dendritic cell, human

 75%|███████▌  | 3/4 [01:13<00:24, 24.58s/it]

filtering for cell type memory regulatory T cell
All cell types are done

 92%|█████████▏| 589/642 [1:09:51<36:59, 41.88s/it]

Processing ed852810-a003-4386-9846-1638362cee39 with size 559821171
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ed852810-a003-4386-9846-1638362cee39.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 40868
filtering
filtering for cell type macrophage
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type monocyte
filtering for cell type mast cell
filtering for cell type mature NK T cell
filtering for cell type dendritic cell
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type CD4-positive, alpha-beta cytotoxic T cell
filtering for cell type activated CD8-positive, alpha-beta T cell
filtering for cell type activated CD4-positive, alpha-beta T cell
filtering for cell type CD14-positive, CD16-positive monocyte

  0%|          | 0/1 [00:18<?, ?it/s]

All cell types are done

 92%|█████████▏| 590/642 [1:10:13<30:58, 35.74s/it]

Processing ed9e9f96-4f08-49d2-bef5-b2c29adf3edc with size 142564671
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ed9e9f96-4f08-49d2-bef5-b2c29adf3edc.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 5696
filtering
filtering for cell type B cell
filtering for cell type plasma cell
filtering for cell type myeloid cell
filtering for cell type neutrophil
filtering for cell type mature NK T cell
filtering for cell type dendritic cell

  0%|          | 0/1 [00:02<?, ?it/s]

filtering for cell type platelet
All cell types are done

 92%|█████████▏| 591/642 [1:10:16<22:09, 26.06s/it]

Processing edc8d3fe-153c-4e3d-8be0-2108d30f8d70 with size 6400196642
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/edc8d3fe-153c-4e3d-8be0-2108d30f8d70.parquet
Found 5 row groups
Indexing row groups for cell types and counts...

100%|██████████| 5/5 [00:04<00:00,  1.01it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/f22b5bde64b44387a44fe06b4fe37aca-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/f22b5bde64b44387a44fe06b4fe37aca-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 42 COLUMNS
At line 240 RHS
At line 278 BOUNDS
At line 284 ENDATA
Problem MODEL has 37 rows, 5 columns and 182 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 5 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 5 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                5.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 5 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type macrophage
filtering for cell type T cell
filtering for cell type B cell
filtering for cell type monocyte
filtering for cell type CD16-positive, CD56-dim natural killer cell, human
filtering for cell type naive B cell
filtering for cell type plasma cell
filtering for cell type memory B cell
filtering for cell type regulatory T cell
filtering for cell type CD8-positive, alpha-beta memory T cell
filtering for cell type neutrophil
filtering for cell type gamma-delta T cell
filtering for cell type mast cell
filtering for cell type mature NK T cell
filtering for cell type secretory cell
filtering for cell type dendritic cell
filtering for cell type conventional dendritic cell
filtering for cell type club cell
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type mucosal invariant T cell
filtering for cell type CD16-negative, CD56-bright natural killer cell, human
filtering for cell type T follicular helper cell
filtering for cell type multi-ciliated epithelial cell
filtering for cell type tracheal goblet cell
filtering for cell type ciliated cell
filtering for cell type innate lymphoid cell
filtering for cell type melanocyte
filtering for cell type basal cell of epithelium of trachea
filtering for cell type naive T cell
filtering for cell type alternatively activated macrophage
filtering for cell type plasmacytoid dendritic cell, human
filtering for cell type neuroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type duct epithelial cell
filtering for cell type squamous epithelial cell

filtering for cell type pulmonary ionocyte
reading row group 1
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type T cell
filtering for cell type CD16-positive, CD56-dim natural killer cell, human
filtering for cell type plasma cell
filtering for cell type regulatory T cell
filtering for cell type neutrophil
filtering for cell type gamma-delta T cell
filtering for cell type mast cell
filtering for cell type mature NK T cell
filtering for cell type conventional dendritic cell
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type mucosal invariant T cell
filtering for cell type CD16-negative, CD56-bright natural killer cell, human
filtering for cell type T follicular helper cell
filtering for cell type multi-ciliated epithelial cell
filtering for cell type innate lymphoid cell
filtering for cell type melanocyte
filtering for cell type basal cell of epithelium of trachea
filtering for cell type naive T cell
filtering for cell type alternatively activated macrophage
filtering for cell type plasmacytoid dendritic cell, human
filtering for cell type neuroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type duct epithelial cell

filtering for cell type squamous epithelial cell
filtering for cell type pulmonary ionocyte
reading row group 2
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type T cell
filtering for cell type CD16-positive, CD56-dim natural killer cell, human
filtering for cell type plasma cell
filtering for cell type regulatory T cell
filtering for cell type neutrophil
filtering for cell type gamma-delta T cell
filtering for cell type mast cell
filtering for cell type mature NK T cell
filtering for cell type conventional dendritic cell
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type mucosal invariant T cell
filtering for cell type CD16-negative, CD56-bright natural killer cell, human
filtering for cell type T follicular helper cell
filtering for cell type multi-ciliated epithelial cell
filtering for cell type innate lymphoid cell
filtering for cell type melanocyte
filtering for cell type naive T cell
filtering for cell type alternatively activated macrophage
filtering for cell type plasmacytoid dendritic cell, human
filtering for cell type neuroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type duct epithelial cell
filtering for cell type squamous epithelial cell
filtering for cell type pulmonary ionocyte

reading row group 3
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type T cell
filtering for cell type CD16-positive, CD56-dim natural killer cell, human
filtering for cell type plasma cell
filtering for cell type regulatory T cell
filtering for cell type neutrophil
filtering for cell type gamma-delta T cell
filtering for cell type mast cell
filtering for cell type mature NK T cell
filtering for cell type conventional dendritic cell
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type mucosal invariant T cell
filtering for cell type CD16-negative, CD56-bright natural killer cell, human
filtering for cell type T follicular helper cell
filtering for cell type multi-ciliated epithelial cell
filtering for cell type innate lymphoid cell
filtering for cell type melanocyte
filtering for cell type naive T cell
filtering for cell type alternatively activated macrophage
filtering for cell type plasmacytoid dendritic cell, human
filtering for cell type neuroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type duct epithelial cell
filtering for cell type squamous epithelial cell
filtering for cell type pulmonary ionocyte

reading row group 4
num rows 36977
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type T cell
filtering for cell type CD16-positive, CD56-dim natural killer cell, human
filtering for cell type regulatory T cell
filtering for cell type neutrophil
filtering for cell type gamma-delta T cell
filtering for cell type mast cell
filtering for cell type mature NK T cell
filtering for cell type conventional dendritic cell
filtering for cell type CD4-positive, alpha-beta memory T cell
filtering for cell type mucosal invariant T cell
filtering for cell type T follicular helper cell
filtering for cell type multi-ciliated epithelial cell
filtering for cell type innate lymphoid cell
filtering for cell type melanocyte
filtering for cell type naive T cell
filtering for cell type alternatively activated macrophage
filtering for cell type plasmacytoid dendritic cell, human
filtering for cell type Langerhans cell
filtering for cell type duct epithelial cell
filtering for cell type squamous epithelial cell

 80%|████████  | 4/5 [01:48<00:27, 27.19s/it]

filtering for cell type pulmonary ionocyte
All cell types are done

/tmp/ipykernel_6603/4260646841.py:116: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_samples = [pd.concat(collected[cell_type], ignore_index=True) for cell_type in collected if collected[cell_type]]
/tmp/ipykernel_6603/4260646841.py:116: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_samples = [pd.concat(collected[cell_type], ignore_index=True) for cell_type in collected if collected[cell_type]]
/tmp/ipykernel_6603/4260646841.py:116: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_samples = [pd.concat(collected[cell_type], ignore_index=True) for cell_type in collected if collected[cell_type]]
/tmp/ipykernel_6603/4260646841.py:116: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_samples = [pd.concat(collected[cell_type], ignore_index=True) for cell_type in collected if collected[cell_type]]
/tmp/ipykernel_6603/4260646841.py:116: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_samples = [pd.concat(collected[cell_type], ignore_index=True) for cell_type in collected if collected[cell_type]]
/tmp/ipykernel_6603/4260646841.py:116: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_samples = [pd.concat(collected[cell_type], ignore_index=True) for cell_type in collected if collected[cell_type]]
 92%|█████████▏| 592/642 [1:12:24<47:09, 56.60s/it]

Processing ee195b7d-184d-4dfa-9b1c-51a7e601ac11 with size 170660816
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ee195b7d-184d-4dfa-9b1c-51a7e601ac11.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 5200
filtering
filtering for cell type B cell
filtering for cell type mesenchymal cell
filtering for cell type enterocyte
filtering for cell type mature NK T cell
filtering for cell type stem cell
filtering for cell type intestine goblet cell
filtering for cell type enteroendocrine cell

  0%|          | 0/1 [00:02<?, ?it/s]

filtering for cell type myeloid leukocyte
filtering for cell type M cell of gut
filtering for cell type precursor cell
All cell types are done

 92%|█████████▏| 593/642 [1:12:28<33:16, 40.74s/it]

Processing eeacb0c1-2217-4cf6-b8ce-1f0fedf1b569 with size 331203356
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/eeacb0c1-2217-4cf6-b8ce-1f0fedf1b569.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 9337
filtering
filtering for cell type B cell
filtering for cell type plasma cell
filtering for cell type myeloid cell
filtering for cell type neutrophil
filtering for cell type mature NK T cell
filtering for cell type dendritic cell
filtering for cell type platelet

  0%|          | 0/1 [00:04<?, ?it/s]

All cell types are done

 93%|█████████▎| 594/642 [1:12:33<24:03, 30.08s/it]

Processing eec3e37d-ed41-4881-bc6e-aaf39a2c6eb0 with size 2487270898
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/eec3e37d-ed41-4881-bc6e-aaf39a2c6eb0.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 42921
filtering
filtering for cell type lamp5 GABAergic cortical interneuron

  0%|          | 0/1 [00:16<?, ?it/s]

All cell types are done

 93%|█████████▎| 595/642 [1:12:50<20:32, 26.23s/it]

Processing eec804b9-2ae5-44f0-a1b5-d721e21257de with size 21983765
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/eec804b9-2ae5-44f0-a1b5-d721e21257de.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 1324
filtering
filtering for cell type B cell
filtering for cell type epithelial cell
filtering for cell type plasma cell
filtering for cell type myeloid cell
filtering for cell type neutrophil
filtering for cell type mast cell
filtering for cell type mature NK T cell

  0%|          | 0/1 [00:01<?, ?it/s]

All cell types are done

 93%|█████████▎| 596/642 [1:12:52<14:28, 18.88s/it]

Processing f156606a-dd9a-49fd-bc40-0e069b6cf07c with size 186006399
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f156606a-dd9a-49fd-bc40-0e069b6cf07c.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 9852
filtering
filtering for cell type B cell
filtering for cell type epithelial cell
filtering for cell type erythrocyte
filtering for cell type myeloid cell
filtering for cell type neutrophil
filtering for cell type mast cell
filtering for cell type mature NK T cell

  0%|          | 0/1 [00:05<?, ?it/s]

filtering for cell type ionocyte
All cell types are done

 93%|█████████▎| 597/642 [1:12:58<11:24, 15.21s/it]

Processing f15e263b-6544-46cb-a46e-e33ab7ce8347 with size 421748475
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f15e263b-6544-46cb-a46e-e33ab7ce8347.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 19722
filtering
filtering for cell type pericyte
filtering for cell type fibroblast of cardiac tissue
filtering for cell type cardiac muscle myoblast
filtering for cell type cardiac endothelial cell
filtering for cell type immature innate lymphoid cell
filtering for cell type lymphoid lineage restricted progenitor cell
filtering for cell type smooth muscle myoblast
filtering for cell type neuronal receptor cell

  0%|          | 0/1 [00:11<?, ?it/s]

All cell types are done

 93%|█████████▎| 598/642 [1:13:14<11:17, 15.39s/it]

Processing f16f4108-7873-4035-9989-3748da1a7ff1 with size 131504654
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f16f4108-7873-4035-9989-3748da1a7ff1.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 4720

  0%|          | 0/1 [00:02<?, ?it/s]

filtering
filtering for cell type oligodendrocyte
All cell types are done

 93%|█████████▎| 599/642 [1:13:17<08:21, 11.67s/it]

Processing f171db61-e57e-4535-a06a-35d8b6ef8f2b with size 1353004992
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f171db61-e57e-4535-a06a-35d8b6ef8f2b.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 37675
filtering
filtering for cell type placental villous trophoblast
filtering for cell type extravillous trophoblast
filtering for cell type syncytiotrophoblast cell

  0%|          | 0/1 [00:20<?, ?it/s]

All cell types are done

 93%|█████████▎| 600/642 [1:13:40<10:34, 15.10s/it]

Processing f1f123cc-ca2c-460f-b7f1-88240efb1e82 with size 263274010
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f1f123cc-ca2c-460f-b7f1-88240efb1e82.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 9471
filtering
filtering for cell type keratinocyte

  0%|          | 0/1 [00:06<?, ?it/s]

All cell types are done

 94%|█████████▎| 601/642 [1:13:48<08:52, 12.98s/it]

Processing f20f44ef-a0d4-4d94-87de-037fd47141f0 with size 1204215876
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f20f44ef-a0d4-4d94-87de-037fd47141f0.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 18728
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type leukocyte
filtering for cell type choroid plexus epithelial cell

  0%|          | 0/1 [00:14<?, ?it/s]

filtering for cell type ependymal cell
All cell types are done

 94%|█████████▍| 602/642 [1:14:04<09:12, 13.82s/it]

Processing f32c2c13-bb1a-4ffd-a457-60b64ecfa4cb with size 8650978510
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f32c2c13-bb1a-4ffd-a457-60b64ecfa4cb.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 116576
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte
filtering for cell type choroid plexus epithelial cell
All cell types are done

  0%|          | 0/1 [01:07<?, ?it/s]
 94%|█████████▍| 603/642 [1:15:13<19:37, 30.19s/it]

Processing f3565fda-499a-4d20-bd92-563c09954c42 with size 1333631110
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f3565fda-499a-4d20-bd92-563c09954c42.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 24155
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:14<?, ?it/s]

filtering for cell type Bergmann glial cell
filtering for cell type ependymal cell
All cell types are done

 94%|█████████▍| 604/642 [1:15:28<16:13, 25.63s/it]

Processing f502c312-05dc-4fd4-a762-92a63e92b539 with size 2344878623
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f502c312-05dc-4fd4-a762-92a63e92b539.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 31230
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:16<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 94%|█████████▍| 605/642 [1:15:45<14:18, 23.20s/it]

Processing f512b8b6-369d-4a85-a695-116e0806857f with size 2055559415
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f512b8b6-369d-4a85-a695-116e0806857f.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 68036
filtering
filtering for cell type keratinocyte
filtering for cell type basal cell of epidermis
filtering for cell type hematopoietic cell
filtering for cell type melanocyte
filtering for cell type prickle cell
filtering for cell type hair follicular keratinocyte

  0%|          | 0/1 [00:39<?, ?it/s]

filtering for cell type Merkel cell
All cell types are done

 94%|█████████▍| 606/642 [1:16:33<18:19, 30.55s/it]

Processing f54647ec-0c03-4775-8dac-5a477c10a3f5 with size 138343054
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f54647ec-0c03-4775-8dac-5a477c10a3f5.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 8753
filtering
filtering for cell type T cell
filtering for cell type natural killer cell
filtering for cell type central memory CD4-positive, alpha-beta T cell
filtering for cell type regulatory T cell
filtering for cell type CD4-positive helper T cell
filtering for cell type CD8-positive, alpha-beta cytotoxic T cell
filtering for cell type T follicular helper cell
filtering for cell type central memory CD8-positive, alpha-beta T cell
filtering for cell type innate lymphoid cell
filtering for cell type T follicular regulatory cell

  0%|          | 0/1 [00:05<?, ?it/s]

All cell types are done

 95%|█████████▍| 607/642 [1:16:40<13:49, 23.69s/it]

Processing f5a04dff-d394-4023-8811-65494e8bb11d with size 2639515675
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f5a04dff-d394-4023-8811-65494e8bb11d.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 34416
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:18<?, ?it/s]

All cell types are done

 95%|█████████▍| 608/642 [1:16:59<12:36, 22.24s/it]

Processing f5be4b96-f5a3-4c3d-84ac-6f69daf744d5 with size 546034471
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f5be4b96-f5a3-4c3d-84ac-6f69daf744d5.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 14903
filtering
filtering for cell type endothelial cell

  0%|          | 0/1 [00:06<?, ?it/s]

All cell types are done

 95%|█████████▍| 609/642 [1:17:06<09:38, 17.54s/it]

Processing f64e1be1-de15-4d27-8da4-82225cd4c035 with size 1347198881
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f64e1be1-de15-4d27-8da4-82225cd4c035.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.94it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/1d69d2cb3cd841359fd355ae52706cac-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/1d69d2cb3cd841359fd355ae52706cac-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 11 COLUMNS
At line 30 RHS
At line 37 BOUNDS
At line 40 ENDATA
Problem MODEL has 6 rows, 2 columns and 12 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.765 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               1
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type T cell
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type plasma cell
filtering for cell type myeloid cell

  0%|          | 0/1 [00:21<?, ?it/s]

filtering for cell type mast cell
All cell types are done

 95%|█████████▌| 610/642 [1:17:29<10:19, 19.36s/it]

Processing f67f2cfa-ba45-4f77-8e26-64a15f666043 with size 668730627
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f67f2cfa-ba45-4f77-8e26-64a15f666043.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 9203

  0%|          | 0/1 [00:03<?, ?it/s]

filtering
filtering for cell type caudal ganglionic eminence derived interneuron
All cell types are done

 95%|█████████▌| 611/642 [1:17:34<07:46, 15.03s/it]

Processing f6d9f2ad-5ec7-4d53-b7f0-ceb0e7bcd181 with size 246372023
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f6d9f2ad-5ec7-4d53-b7f0-ceb0e7bcd181.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 6877
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte

  0%|          | 0/1 [00:03<?, ?it/s]

All cell types are done

 95%|█████████▌| 612/642 [1:17:39<05:52, 11.75s/it]

Processing f6dafdd1-d746-407e-8019-4470e02d4cbd with size 49648764
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f6dafdd1-d746-407e-8019-4470e02d4cbd.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 3699
filtering
filtering for cell type naive B cell
filtering for cell type memory B cell
filtering for cell type IgA plasma cell

  0%|          | 0/1 [00:02<?, ?it/s]

filtering for cell type plasmablast
filtering for cell type IgG plasma cell
All cell types are done

 95%|█████████▌| 613/642 [1:17:42<04:31,  9.35s/it]

Processing f72958f5-7f42-4ebb-98da-445b0c6de516 with size 15079737292
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f72958f5-7f42-4ebb-98da-445b0c6de516.parquet
Found 12 row groups
Indexing row groups for cell types and counts...

100%|██████████| 12/12 [00:12<00:00,  1.03s/it]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/4103a181b2f14a9699cc1b6895fe0701-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/4103a181b2f14a9699cc1b6895fe0701-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 25 COLUMNS
At line 302 RHS
At line 323 BOUNDS
At line 336 ENDATA
Problem MODEL has 20 rows, 12 columns and 240 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 12 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 12 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                12.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 12 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type T cell
filtering for cell type B cell
filtering for cell type monocyte
filtering for cell type capillary endothelial cell
filtering for cell type pulmonary alveolar type 2 cell
filtering for cell type vein endothelial cell
filtering for cell type basal cell
filtering for cell type endothelial cell of artery
filtering for cell type mast cell
filtering for cell type secretory cell
filtering for cell type dendritic cell
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type pulmonary alveolar type 1 cell
filtering for cell type myofibroblast cell
filtering for cell type multi-ciliated epithelial cell
filtering for cell type lung secretory cell
filtering for cell type tracheobronchial smooth muscle cell
filtering for cell type NKp46-positive innate lymphoid cell, human

reading row group 1
num rows 50000
filtering
filtering for cell type pulmonary alveolar type 1 cell
filtering for cell type myofibroblast cell
filtering for cell type lung secretory cell
filtering for cell type tracheobronchial smooth muscle cell
filtering for cell type NKp46-positive innate lymphoid cell, human

reading row group 2
num rows 50000
filtering
filtering for cell type pulmonary alveolar type 1 cell
filtering for cell type myofibroblast cell
filtering for cell type lung secretory cell
filtering for cell type tracheobronchial smooth muscle cell

filtering for cell type NKp46-positive innate lymphoid cell, human
reading row group 3
num rows 50000
filtering
filtering for cell type myofibroblast cell
filtering for cell type lung secretory cell
filtering for cell type tracheobronchial smooth muscle cell

filtering for cell type NKp46-positive innate lymphoid cell, human
reading row group 4
num rows 50000
filtering
filtering for cell type myofibroblast cell
filtering for cell type lung secretory cell
filtering for cell type tracheobronchial smooth muscle cell

filtering for cell type NKp46-positive innate lymphoid cell, human
reading row group 5
num rows 50000
filtering
filtering for cell type myofibroblast cell
filtering for cell type lung secretory cell
filtering for cell type tracheobronchial smooth muscle cell
filtering for cell type NKp46-positive innate lymphoid cell, human

reading row group 6
num rows 50000
filtering
filtering for cell type myofibroblast cell
filtering for cell type lung secretory cell
filtering for cell type tracheobronchial smooth muscle cell
filtering for cell type NKp46-positive innate lymphoid cell, human

reading row group 7
num rows 50000
filtering
filtering for cell type myofibroblast cell

filtering for cell type lung secretory cell
filtering for cell type tracheobronchial smooth muscle cell
reading row group 8
num rows 50000
filtering
filtering for cell type lung secretory cell

filtering for cell type tracheobronchial smooth muscle cell
reading row group 9
num rows 50000
filtering
filtering for cell type tracheobronchial smooth muscle cell

reading row group 10
num rows 50000
filtering

filtering for cell type tracheobronchial smooth muscle cell
reading row group 11
num rows 34884
filtering

 92%|█████████▏| 11/12 [04:02<00:22, 22.01s/it]

filtering for cell type tracheobronchial smooth muscle cell
All cell types are done

 96%|█████████▌| 614/642 [1:22:04<39:38, 84.96s/it]

Processing f75f2ff4-2884-4c2d-b375-70de37a34507 with size 90637560
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f75f2ff4-2884-4c2d-b375-70de37a34507.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 3799

  0%|          | 0/1 [00:01<?, ?it/s]

filtering
filtering for cell type epicardial adipocyte
All cell types are done

 96%|█████████▌| 615/642 [1:22:06<27:07, 60.27s/it]

Processing f7995301-7551-4e1d-8396-ffe3c9497ace with size 8856750146
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f7995301-7551-4e1d-8396-ffe3c9497ace.parquet
Found 7 row groups
Indexing row groups for cell types and counts...

100%|██████████| 7/7 [00:06<00:00,  1.11it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/1f2c3597f77c479db32377848ec9bb08-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/1f2c3597f77c479db32377848ec9bb08-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 35 RHS
At line 37 BOUNDS
At line 45 ENDATA
Problem MODEL has 1 rows, 7 columns and 7 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.03332 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 6
num rows 11418
filtering
filtering for cell type cardiac muscle cell

  0%|          | 0/1 [00:04<?, ?it/s]

All cell types are done

 96%|█████████▌| 616/642 [1:22:18<19:45, 45.59s/it]

Processing f7ca7eb9-0919-4eba-99a1-21ba382b4174 with size 769532578
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f7ca7eb9-0919-4eba-99a1-21ba382b4174.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 11103
filtering
filtering for cell type neuron
filtering for cell type enterocyte
filtering for cell type transit amplifying cell
filtering for cell type mesenchymal stem cell
filtering for cell type myofibroblast cell
filtering for cell type goblet cell
filtering for cell type enteroendocrine cell
filtering for cell type paneth cell

  0%|          | 0/1 [00:04<?, ?it/s]

All cell types are done

 96%|█████████▌| 617/642 [1:22:24<14:06, 33.88s/it]

Processing f7d003d4-40d5-4de8-858c-a9a8b48fcc67 with size 4815805895
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f7d003d4-40d5-4de8-858c-a9a8b48fcc67.parquet
Found 4 row groups
Indexing row groups for cell types and counts...

100%|██████████| 4/4 [00:03<00:00,  1.18it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/129f51920318433094bb4b3dd2616385-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/129f51920318433094bb4b3dd2616385-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 23 RHS
At line 25 BOUNDS
At line 30 ENDATA
Problem MODEL has 1 rows, 4 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.00158 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 3
num rows 5025

  0%|          | 0/1 [00:01<?, ?it/s]

filtering
filtering for cell type astrocyte
All cell types are done

 96%|█████████▋| 618/642 [1:22:30<10:08, 25.35s/it]

Processing f7ec7bd5-04ab-453b-a8a7-c9d14812affb with size 818396645
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f7ec7bd5-04ab-453b-a8a7-c9d14812affb.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 32926
filtering
filtering for cell type stromal cell

  0%|          | 0/1 [00:12<?, ?it/s]

All cell types are done

 96%|█████████▋| 619/642 [1:22:43<08:22, 21.84s/it]

Processing f801b7a9-80a6-4d09-9161-71474deb58ae with size 136691654
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f801b7a9-80a6-4d09-9161-71474deb58ae.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 6044
filtering
filtering for cell type macrophage
filtering for cell type T cell
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type monocyte
filtering for cell type pericyte
filtering for cell type epithelial cell of proximal tubule
filtering for cell type kidney loop of Henle thick ascending limb epithelial cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type kidney distal convoluted tubule epithelial cell
filtering for cell type podocyte
filtering for cell type renal alpha-intercalated cell
filtering for cell type renal principal cell
filtering for cell type renal beta-intercalated cell
filtering for cell type glomerular capillary endothelial cell
filtering for cell type mesangial cell
filtering for cell type vasa recta ascending limb cell

  0%|          | 0/1 [00:03<?, ?it/s]

filtering for cell type vasa recta descending limb cell
filtering for cell type kidney collecting duct cell
All cell types are done

 97%|█████████▋| 620/642 [1:22:48<06:07, 16.69s/it]

Processing f854421b-d231-4231-9b23-fc3be7fbee45 with size 446590049
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f854421b-d231-4231-9b23-fc3be7fbee45.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 19317
filtering
filtering for cell type capillary endothelial cell
filtering for cell type pericyte
filtering for cell type mural cell
filtering for cell type vein endothelial cell
filtering for cell type endothelial cell of artery
filtering for cell type blood vessel endothelial cell
filtering for cell type endothelial cell of lymphatic vessel
filtering for cell type smooth muscle cell

  0%|          | 0/1 [00:07<?, ?it/s]

filtering for cell type endothelial cell of arteriole
All cell types are done

 97%|█████████▋| 621/642 [1:22:57<05:03, 14.45s/it]

Processing f8c77961-67a7-4161-b8c2-61c3f917b54f with size 171075075
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f8c77961-67a7-4161-b8c2-61c3f917b54f.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 6101
filtering
filtering for cell type amacrine cell
filtering for cell type glycinergic amacrine cell

  0%|          | 0/1 [00:02<?, ?it/s]

filtering for cell type starburst amacrine cell
filtering for cell type A2 amacrine cell
All cell types are done

 97%|█████████▋| 622/642 [1:23:01<03:44, 11.22s/it]

Processing f8d8b443-bca6-4c3c-9042-669dfb7f8030 with size 1043851516
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f8d8b443-bca6-4c3c-9042-669dfb7f8030.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 33041
filtering

  0%|          | 0/1 [00:11<?, ?it/s]

filtering for cell type microglial cell
All cell types are done

 97%|█████████▋| 623/642 [1:23:14<03:42, 11.71s/it]

Processing f8dda921-5fb4-4c94-a654-c6fc346bfd6d with size 2146968885
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f8dda921-5fb4-4c94-a654-c6fc346bfd6d.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 31899
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:12<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 97%|█████████▋| 624/642 [1:23:26<03:36, 12.01s/it]

Processing f9034091-2e8f-4ac6-9874-e7b7eb566824 with size 1312427664
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f9034091-2e8f-4ac6-9874-e7b7eb566824.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 23120
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell
filtering for cell type leukocyte
filtering for cell type Bergmann glial cell
filtering for cell type choroid plexus epithelial cell
filtering for cell type ependymal cell

  0%|          | 0/1 [00:09<?, ?it/s]

All cell types are done

 97%|█████████▋| 625/642 [1:23:36<03:13, 11.37s/it]

Processing f9846bb4-784d-4582-92c1-3f279e4c6f0c with size 1368114558
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f9846bb4-784d-4582-92c1-3f279e4c6f0c.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 39204
filtering
filtering for cell type fibroblast
filtering for cell type mesenchymal cell
filtering for cell type pericyte
filtering for cell type smooth muscle cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type mesothelial cell
filtering for cell type myofibroblast cell
filtering for cell type fibroblast of lung
filtering for cell type chondrocyte
filtering for cell type tracheobronchial smooth muscle cell
filtering for cell type pulmonary interstitial fibroblast

  0%|          | 0/1 [00:15<?, ?it/s]

All cell types are done

 98%|█████████▊| 626/642 [1:23:55<03:37, 13.62s/it]

Processing f9ad5649-f372-43e1-a3a8-423383e5a8a2 with size 60475468
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f9ad5649-f372-43e1-a3a8-423383e5a8a2.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 8168
filtering
filtering for cell type oligodendrocyte

  0%|          | 0/1 [00:03<?, ?it/s]

All cell types are done

 98%|█████████▊| 627/642 [1:23:59<02:40, 10.73s/it]

Processing f9cfac8d-bff6-47a2-a1f6-503827d375f5 with size 16382637
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/f9cfac8d-bff6-47a2-a1f6-503827d375f5.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 637

  0%|          | 0/1 [00:00<?, ?it/s]

filtering
filtering for cell type vascular leptomeningeal cell
All cell types are done

 98%|█████████▊| 628/642 [1:24:01<01:51,  7.93s/it]

Processing fa3e2a80-1c9a-4097-a02f-bf47e143fca7 with size 6837024927
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fa3e2a80-1c9a-4097-a02f-bf47e143fca7.parquet
Found 4 row groups
Indexing row groups for cell types and counts...

100%|██████████| 4/4 [00:03<00:00,  1.19it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/517dd68418d047c197c68fb07d2d0eeb-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/517dd68418d047c197c68fb07d2d0eeb-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 23 RHS
At line 25 BOUNDS
At line 30 ENDATA
Problem MODEL has 1 rows, 4 columns and 4 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 0.006 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 1 strengthened rows, 0 substitutions
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 1 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                1.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 1 row groups ...

reading row group 3
num rows 35226
filtering

  0%|          | 0/1 [00:15<?, ?it/s]

filtering for cell type CD8-positive, alpha-beta T cell
All cell types are done

 98%|█████████▊| 629/642 [1:24:21<02:33, 11.78s/it]

Processing fa554686-fc07-44dd-b2de-b726d82d26ec with size 2074544209
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fa554686-fc07-44dd-b2de-b726d82d26ec.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 29674
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:13<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 98%|█████████▊| 630/642 [1:24:36<02:30, 12.53s/it]

Processing fa8605cf-f27e-44af-ac2a-476bee4410d3 with size 1036286642
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fa8605cf-f27e-44af-ac2a-476bee4410d3.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:01<00:00,  1.54it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/9add307f42164e8c8727cf6611e83b1f-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/9add307f42164e8c8727cf6611e83b1f-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 15 COLUMNS
At line 42 RHS
At line 53 BOUNDS
At line 56 ENDATA
Problem MODEL has 10 rows, 2 columns and 20 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 1.58947 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 2 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.00000000
Enumerated nodes:               0
Total iterations:               2
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 2 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type CD4-positive, alpha-beta T cell
filtering for cell type CD8-positive, alpha-beta T cell
filtering for cell type natural killer cell
filtering for cell type B cell
filtering for cell type monocyte
filtering for cell type dendritic cell
filtering for cell type plasmacytoid dendritic cell
filtering for cell type platelet
filtering for cell type plasmablast

filtering for cell type alpha-beta T cell
reading row group 1
num rows 9506
filtering
filtering for cell type plasmacytoid dendritic cell
filtering for cell type platelet
filtering for cell type plasmablast

 50%|█████     | 1/2 [00:25<00:25, 25.43s/it]

All cell types are done

 98%|█████████▊| 631/642 [1:25:06<03:17, 17.92s/it]

Processing faed4f71-6b50-4fc7-bd1c-8f385dccfdce with size 63357963
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/faed4f71-6b50-4fc7-bd1c-8f385dccfdce.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 3951
filtering
filtering for cell type capillary endothelial cell
filtering for cell type vein endothelial cell
filtering for cell type endothelial cell of artery

  0%|          | 0/1 [00:01<?, ?it/s]

All cell types are done

 98%|█████████▊| 632/642 [1:25:09<02:15, 13.53s/it]

Processing fbf173f9-f809-4d84-9b65-ae205d35b523 with size 746585344
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fbf173f9-f809-4d84-9b65-ae205d35b523.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 17660
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:08<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

 99%|█████████▊| 633/642 [1:25:19<01:52, 12.47s/it]

Processing fc0ceb80-d2d9-47c1-9d78-b0e45c64c500 with size 116552164
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fc0ceb80-d2d9-47c1-9d78-b0e45c64c500.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 1877

  0%|          | 0/1 [00:00<?, ?it/s]

filtering
filtering for cell type sst GABAergic cortical interneuron
All cell types are done

 99%|█████████▉| 634/642 [1:25:22<01:16,  9.52s/it]

Processing fd072bc3-2dfb-46f8-b4e3-467cb3223182 with size 26767967967
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fd072bc3-2dfb-46f8-b4e3-467cb3223182.parquet
Found 19 row groups
Indexing row groups for cell types and counts...

100%|██████████| 19/19 [00:19<00:00,  1.00s/it]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/f622d526a87a4bb1b216f97363aa06a5-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/f622d526a87a4bb1b216f97363aa06a5-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 70 COLUMNS
At line 1271 RHS
At line 1337 BOUNDS
At line 1357 ENDATA
Problem MODEL has 65 rows, 19 columns and 1143 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 19 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 19 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                19.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 19 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type neuron
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type T cell
filtering for cell type natural killer cell
filtering for cell type endothelial cell
filtering for cell type naive thymus-derived CD4-positive, alpha-beta T cell
filtering for cell type monocyte
filtering for cell type epithelial cell
filtering for cell type erythrocyte
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type naive thymus-derived CD8-positive, alpha-beta T cell
filtering for cell type double-positive, alpha-beta thymocyte
filtering for cell type regulatory T cell
filtering for cell type double negative thymocyte
filtering for cell type neutrophil
filtering for cell type mast cell
filtering for cell type dendritic cell
filtering for cell type smooth muscle cell
filtering for cell type vascular associated smooth muscle cell
filtering for cell type mesothelial cell
filtering for cell type hepatocyte
filtering for cell type keratinocyte
filtering for cell type myofibroblast cell
filtering for cell type glial cell
filtering for cell type plasmacytoid dendritic cell
filtering for cell type chondrocyte
filtering for cell type megakaryocyte
filtering for cell type granulocyte
filtering for cell type promonocyte
filtering for cell type hematopoietic stem cell
filtering for cell type innate lymphoid cell
filtering for cell type B-2 B cell
filtering for cell type pro-B cell
filtering for cell type mature B cell
filtering for cell type Kupffer cell
filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type hematopoietic multipotent progenitor cell
filtering for cell type granulocyte monocyte progenitor cell
filtering for cell type melanocyte
filtering for cell type large pre-B-II cell
filtering for cell type immature B cell
filtering for cell type late pro-B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 1
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type double negative thymocyte
filtering for cell type neutrophil
filtering for cell type mast cell
filtering for cell type mesothelial cell
filtering for cell type hepatocyte
filtering for cell type keratinocyte
filtering for cell type glial cell
filtering for cell type plasmacytoid dendritic cell
filtering for cell type chondrocyte
filtering for cell type megakaryocyte
filtering for cell type granulocyte
filtering for cell type promonocyte
filtering for cell type hematopoietic stem cell
filtering for cell type innate lymphoid cell
filtering for cell type B-2 B cell
filtering for cell type pro-B cell
filtering for cell type mature B cell
filtering for cell type Kupffer cell
filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type hematopoietic multipotent progenitor cell
filtering for cell type granulocyte monocyte progenitor cell
filtering for cell type melanocyte
filtering for cell type large pre-B-II cell
filtering for cell type immature B cell
filtering for cell type late pro-B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 2
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type double negative thymocyte
filtering for cell type neutrophil
filtering for cell type mesothelial cell
filtering for cell type hepatocyte
filtering for cell type keratinocyte
filtering for cell type glial cell
filtering for cell type plasmacytoid dendritic cell
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type promonocyte
filtering for cell type hematopoietic stem cell
filtering for cell type innate lymphoid cell
filtering for cell type B-2 B cell
filtering for cell type pro-B cell
filtering for cell type mature B cell
filtering for cell type Kupffer cell
filtering for cell type megakaryocyte-erythroid progenitor cell
filtering for cell type hematopoietic multipotent progenitor cell
filtering for cell type granulocyte monocyte progenitor cell
filtering for cell type melanocyte
filtering for cell type large pre-B-II cell
filtering for cell type immature B cell
filtering for cell type late pro-B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell

filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor
filtering for cell type eurydendroid cell
reading row group 3
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type double negative thymocyte
filtering for cell type neutrophil
filtering for cell type mesothelial cell
filtering for cell type hepatocyte
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type promonocyte
filtering for cell type innate lymphoid cell
filtering for cell type B-2 B cell
filtering for cell type pro-B cell
filtering for cell type mature B cell
filtering for cell type hematopoietic multipotent progenitor cell
filtering for cell type granulocyte monocyte progenitor cell
filtering for cell type melanocyte
filtering for cell type large pre-B-II cell
filtering for cell type immature B cell
filtering for cell type late pro-B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell

filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor
filtering for cell type eurydendroid cell
reading row group 4
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type double negative thymocyte
filtering for cell type neutrophil
filtering for cell type mesothelial cell
filtering for cell type hepatocyte
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type promonocyte
filtering for cell type innate lymphoid cell
filtering for cell type pro-B cell
filtering for cell type mature B cell
filtering for cell type granulocyte monocyte progenitor cell
filtering for cell type melanocyte
filtering for cell type large pre-B-II cell
filtering for cell type immature B cell
filtering for cell type late pro-B cell
filtering for cell type group 3 innate lymphoid cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type CD8-alpha-alpha-positive, alpha-beta intraepithelial T cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell

filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor
filtering for cell type eurydendroid cell
reading row group 5
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type neutrophil
filtering for cell type mesothelial cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type granulocyte monocyte progenitor cell
filtering for cell type melanocyte
filtering for cell type large pre-B-II cell
filtering for cell type immature B cell
filtering for cell type late pro-B cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 6
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type neutrophil
filtering for cell type mesothelial cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type granulocyte monocyte progenitor cell
filtering for cell type melanocyte
filtering for cell type large pre-B-II cell
filtering for cell type immature B cell
filtering for cell type late pro-B cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 7
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type neutrophil
filtering for cell type mesothelial cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type granulocyte monocyte progenitor cell
filtering for cell type melanocyte
filtering for cell type large pre-B-II cell
filtering for cell type immature B cell
filtering for cell type late pro-B cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 8
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type mesothelial cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type granulocyte monocyte progenitor cell
filtering for cell type melanocyte
filtering for cell type large pre-B-II cell
filtering for cell type immature B cell
filtering for cell type late pro-B cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 9
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type mesothelial cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type melanocyte
filtering for cell type immature B cell
filtering for cell type small pre-B-II cell
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor
filtering for cell type eurydendroid cell

reading row group 10
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type mesothelial cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type melanocyte
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type fraction A pre-pro B cell
filtering for cell type osteoblast
filtering for cell type B-1 B cell
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 11
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type melanocyte
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type epithelial cell of nephron
filtering for cell type osteoblast
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor
filtering for cell type eurydendroid cell

reading row group 12
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type melanocyte
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type osteoblast
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type promyelocyte
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 13
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type granulocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type melanocyte
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type osteoblast
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 14
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type keratinocyte
filtering for cell type chondrocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type melanocyte
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type osteoblast
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor
filtering for cell type eurydendroid cell

reading row group 15
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type chondrocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type melanocyte
filtering for cell type skeletal muscle satellite cell
filtering for cell type common myeloid progenitor
filtering for cell type osteoblast
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal

filtering for cell type common dendritic progenitor
filtering for cell type eurydendroid cell
reading row group 16
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type chondrocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type melanocyte
filtering for cell type skeletal muscle satellite cell
filtering for cell type osteoblast
filtering for cell type enteroendocrine cell
filtering for cell type Langerhans cell
filtering for cell type myelocyte
filtering for cell type early lymphoid progenitor
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type osteoclast
filtering for cell type pre-conventional dendritic cell
filtering for cell type interstitial cell of Cajal
filtering for cell type common dendritic progenitor

filtering for cell type eurydendroid cell
reading row group 17
num rows 50000
filtering
filtering for cell type plasma cell
filtering for cell type stromal cell
filtering for cell type chondrocyte
filtering for cell type innate lymphoid cell
filtering for cell type mature B cell
filtering for cell type melanocyte
filtering for cell type myelocyte
filtering for cell type cell of skeletal muscle
filtering for cell type group 2 innate lymphoid cell
filtering for cell type pre-conventional dendritic cell
filtering for cell type common dendritic progenitor
filtering for cell type eurydendroid cell

reading row group 18
num rows 8046
filtering
filtering for cell type stromal cell
filtering for cell type melanocyte
filtering for cell type cell of skeletal muscle

 95%|█████████▍| 18/19 [07:38<00:25, 25.49s/it]

All cell types are done

 99%|█████████▉| 635/642 [1:33:50<18:32, 158.93s/it]

Processing fd89be61-2869-4342-a86e-e1fce3a8f269 with size 706641973
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fd89be61-2869-4342-a86e-e1fce3a8f269.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 17622
filtering
filtering for cell type enterocyte
filtering for cell type secretory cell
filtering for cell type progenitor cell
filtering for cell type intestine goblet cell
filtering for cell type transit amplifying cell of colon
filtering for cell type enteroendocrine cell
filtering for cell type transit amplifying cell of small intestine
filtering for cell type gut absorptive cell
filtering for cell type intestinal crypt stem cell of large intestine
filtering for cell type intestinal crypt stem cell of small intestine

  0%|          | 0/1 [00:10<?, ?it/s]

All cell types are done

 99%|█████████▉| 636/642 [1:34:05<11:34, 115.76s/it]

Processing fe1a73ab-a203-45fd-84e9-0f7fd19efcbd with size 2270929094
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fe1a73ab-a203-45fd-84e9-0f7fd19efcbd.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 35285
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:18<?, ?it/s]

filtering for cell type leukocyte
filtering for cell type ependymal cell
All cell types are done

 99%|█████████▉| 637/642 [1:34:25<07:15, 87.14s/it]

Processing fe2eecbc-977a-4aec-9196-f89c3281d11c with size 35673440
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fe2eecbc-977a-4aec-9196-f89c3281d11c.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 1621
filtering
filtering for cell type microglial cell

  0%|          | 0/1 [00:01<?, ?it/s]

All cell types are done

 99%|█████████▉| 638/642 [1:34:27<04:06, 61.60s/it]

Processing fe4b89d5-461e-440c-a5a8-621b37b122c0 with size 2649526346
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fe4b89d5-461e-440c-a5a8-621b37b122c0.parquet
Found 4 row groups
Indexing row groups for cell types and counts...

100%|██████████| 4/4 [00:03<00:00,  1.01it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/40b02b6b2d7e4cc6b450bf9c4ca3e98e-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/40b02b6b2d7e4cc6b450bf9c4ca3e98e-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 13 COLUMNS
At line 58 RHS
At line 67 BOUNDS
At line 72 ENDATA
Problem MODEL has 8 rows, 4 columns and 32 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 4 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 4 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                4.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 4 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type epithelial cell
filtering for cell type enterocyte
filtering for cell type stem cell
filtering for cell type goblet cell
filtering for cell type paneth cell
filtering for cell type brush cell
filtering for cell type type EC enteroendocrine cell
filtering for cell type type L enteroendocrine cell

reading row group 1
num rows 50000
filtering
filtering for cell type paneth cell
filtering for cell type brush cell
filtering for cell type type EC enteroendocrine cell
filtering for cell type type L enteroendocrine cell

reading row group 2
num rows 50000
filtering
filtering for cell type paneth cell
filtering for cell type brush cell
filtering for cell type type EC enteroendocrine cell
filtering for cell type type L enteroendocrine cell

reading row group 3
num rows 4136
filtering
filtering for cell type paneth cell
filtering for cell type brush cell
filtering for cell type type EC enteroendocrine cell

 75%|███████▌  | 3/4 [01:16<00:25, 25.58s/it]

filtering for cell type type L enteroendocrine cell
All cell types are done

100%|█████████▉| 639/642 [1:35:53<03:27, 69.05s/it]

Processing fe52003e-1460-4a65-a213-2bb1a508332f with size 1923793822
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/fe52003e-1460-4a65-a213-2bb1a508332f.parquet
Found 2 row groups
Indexing row groups for cell types and counts...

100%|██████████| 2/2 [00:00<00:00,  2.12it/s]

Selecting optimal row groups using ILP...
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /root/GenePT-tools/.venv/lib/python3.12/site-packages/pulp/apis/../solverdir/cbc/linux/i64/cbc /tmp/f30d5bbcc1654f9ab8412bb2c01638b5-pulp.mps -timeMode elapsed -branch -printingOptions all -solution /tmp/f30d5bbcc1654f9ab8412bb2c01638b5-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 11 COLUMNS
At line 30 RHS
At line 37 BOUNDS
At line 40 ENDATA
Problem MODEL has 6 rows, 2 columns and 12 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 2 - 0.00 seconds
Cgl0004I processed model has 0 rows, 0 columns (0 integer (0 of which binary)) and 0 elements
Cbc3007W No integer variables - nothing to do
Cuts at root node changed objective from 2 to -1.79769e+308
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                2.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.00   (Wallclock seconds):       0.00

Reading 2 row groups ...

reading row group 0
num rows 50000
filtering
filtering for cell type macrophage
filtering for cell type classical monocyte
filtering for cell type alveolar macrophage
filtering for cell type non-classical monocyte
filtering for cell type conventional dendritic cell

filtering for cell type dendritic cell, human
reading row group 1
num rows 1552

 50%|█████     | 1/2 [00:25<00:25, 25.92s/it]

filtering
filtering for cell type dendritic cell, human
All cell types are done

100%|█████████▉| 640/642 [1:36:23<01:54, 57.07s/it]

Processing ff4cfa86-9c0c-4b7c-abd6-90547657d04f with size 246620277
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ff4cfa86-9c0c-4b7c-abd6-90547657d04f.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 9799
filtering
filtering for cell type fibroblast
filtering for cell type macrophage
filtering for cell type T cell
filtering for cell type malignant cell
filtering for cell type blood vessel endothelial cell
filtering for cell type blood vessel smooth muscle cell
filtering for cell type cell of skeletal muscle

  0%|          | 0/1 [00:05<?, ?it/s]

All cell types are done

100%|█████████▉| 641/642 [1:36:30<00:42, 42.12s/it]

Processing ff7d15fa-f4b6-4a0e-992e-fd0c9d088ded with size 2013071830
Opening s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/ff7d15fa-f4b6-4a0e-992e-fd0c9d088ded.parquet
Found 1 row groups
Reading 1 row groups ...

reading row group 0
num rows 28051
filtering
filtering for cell type neuron
filtering for cell type oligodendrocyte
filtering for cell type fibroblast
filtering for cell type endothelial cell
filtering for cell type astrocyte
filtering for cell type oligodendrocyte precursor cell
filtering for cell type pericyte
filtering for cell type central nervous system macrophage
filtering for cell type vascular associated smooth muscle cell

  0%|          | 0/1 [00:13<?, ?it/s]

filtering for cell type leukocyte
All cell types are done

100%|██████████| 642/642 [1:36:45<00:00,  9.04s/it]

In [376]:
embedding_path = "s3://pythiomicsdata/cellxgene_v2/genept_embeddings_v1/0ae6f031-2f9c-4247-8b26-db320d6efd32.parquet"

with fs.open(embedding_path, 'rb') as f:
  embeddings_pdf = pd.read_parquet(f)

In [ ]:
embeddings_pdf.assay.value_counts()